docs/source/design.rst

Left one place as "IO" due to multiple slashes being used as a separator in a phrase already.

Normalize use "I/O"

---

docs/source/reference-core.rst

I believe this PR fixes the broken example in the Custom Supervisor example in the docs, where ``finished_task`` is an undeclared variable and ``reap_and_unwrap`` should be called on the ``nursery``.
While this is a solid example and this PR should fix the immediate error, I was wondering if you would be open to making this example a little more expressive. For me, this type of monitoring demonstrates some of the most elegant parts of the trio API. What I had in mind would be expanding the example to something like
```python
import functools
import trio
async def sleep_and_return_num(num):
await trio.sleep(num)
return num
async def race(*async_fns):
if not async_fns:
raise ValueError("must pass at least one argument")
async with trio.open_nursery() as nursery:
for async_fn in async_fns: …
```

Fix custom supervisor example in documentation

---

trio/_core/_io_windows.py
trio/_core/_wakeup_socketpair.py

As compared to the CFFI-based code that this replaces, it's (a) less
race-y (the Python C-level signal handler writes to the
wakeup_fd *after* setting the flag to run the Python-level signal
handler, whereas our old code ran before), (b) avoids arcane CFFI
stuff that might be broken in the presence of subinterpreters, (c)
slightly less code.
The downside of set_wakeup_fd is that writing to the wakeup socket
fails with EWOULDBLOCK, then in our context the correct thing to do is
to ignore that error (we just want to guarantee a wakeup, and if the
send buffer is full then we are definitely going to wake up), but the
hardcoded behavior in signalmodule.c is to print a spurious warning to
stderr. IMO this is makes it useless to us on Unix-likes, because they
get signals all the time, and we …

Use set_wakeup_fd to react to control-C on Windows

---

notes-to-self/manual-signal-handler.py
trio/_core/tests/test_ki.py
trio/_signals.py
trio/_util.py
trio/tests/test_signals.py
trio/tests/test_util.py

This patch looks larger than it is, because it refactors the code to
send a signal to our own process into trio._util.signal_raise. The
only really new bit is trio._core.tests.test_ki.test_ki_wakes_us_up.

Add a test for control-C waking us up

---

docs/source/conf.py

This should fix the travis doc builds, that were broken by the 1.5.5
release coming out without the patch...

Assume that all sphinxes < 1.6 will need monkeypatching

---

trio/_core/tests/tutil.py

Depending on pytest is called, it sometimes doesn't pick up our
--run-slow option. I find this sorta weird and mysterious, and
probably we should come up with a more robust workaround, but in the
mean time this commit should make it so that if it doesn't notice
--run-slow then it defaults to assuming its passed, instead of
crashing.

[test] Make '--run-slow' option default to true if unregistered

---

docs/source/history.rst
docs/source/reference-core.rst
trio/_core/_ki.py
trio/_core/_run.py
trio/_core/tests/test_ki.py

There are two main strategies for handling control-C:
- Accept that a KeyboardInterrupt will be raised "asynchronously" (in
the sense of "asynchronous exceptions", nothing to do with
async/await). It's essentially impossible to write fully correct
code under this model (see many rants by Java folks), but it does
something more-or-less reasonable 99% of the time, and it's what
Python developers expect.
- Use some sort of explicit handler for KeyboardInterrupt, and only
deal with them at carefully chosen places in your code where you
know it's safe to do so. This makes it possible to write fully
correct code, but doesn't make it easy; such code tends to be
difficult to write and fragile. It's not *as* bad in trio because we
have nice abstractions like cancellation and trio.catch_signals, …

New argument to trio.run: restrict_keyboard_interrupt_to_checkpoints

---

trio/_util.py

This works as a hint to sphinxcontrib-trio that functions decorated
with @acontextmanager should be documented as async context managers,
and *not* async iterators (like they're currently being detected).
See: https://github.com/python-trio/sphinxcontrib-trio/commit/2d9e65187dc7a08863b68a78bdee4fb051f0b99e

Set __returns_acontextmanager__ = True in @acontextmanager

---

docs/source/tutorial.rst
trio/_core/tests/test_ki.py

In v1.7, async_generator.isasyncgenfunction became pickier, to match
inspect.isasyncgenfunction and because this was needed to fix the trio
docs. Apparently this bit of trio's test suite was relying on the old
laxity...
In general we could also make acontextmanager more lenient, and that
might make sense if it were a public API, but for now the extra
pickiness seems fine.

Fix test broken by async_generator 1.7 release

---

trio/_core/tests/test_ki.py

It failed yet again, even with all our countermeasures:
https://ci.appveyor.com/project/njsmith/trio/build/1.0.341/job/r356mgh7mi103lip
Current theory: the two ki_self()'s are running, and each is
synchronously running the C-level signal handler in the kill_soon
thread (because ki_self() uses raise() and I think it works like
that). And then the main thread is taking the lock, to try to
guarantee that it runs some inside the test after *both* ki_self()'s,
so that any Python-level handlers that are going to run, run inside
the test.
But, maybe somehow the main thread is not noticing that the C-level
handler has requested that the Python-level handler be run, because
PyEval_EvalFrameEx only checks every once in a while? I'm skeptical
because it's supposed to notice promptly after the …

Yet another attempt to make test_ki_wakes_us_up reliable on Windows

---

trio/_core/_multierror.py
trio/_core/tests/test_multierror.py

Python's implicit exception chaining logic insists on corrupting
__context__ when we re-raise an unpacked exception in
MultiError.catch. This commit introduces a counter-measure.

Correctly preserve exception __context__ in MultiError.catch

---

trio/socket.py
trio/tests/test_socket.py

~This doesn't appear to work with all types of AF_INET6 sockets--it is likely better to have the caller handle this instead.~ I've now changed this to ignore OSError instead based on your feedback in #164.
Fixes #164.

socket: ignore OSError during IPV6_V6ONLY-normalization

---

docs/source/reference-core.rst
docs/source/reference-core/tasklocal-example.py
docs/source/reference-hazmat.rst
trio/_core/__init__.py
trio/_core/_local.py
trio/_core/_run.py
trio/_core/tests/test_local.py

Add task- and run-local storage.

---

trio/_core/_run.py
trio/_core/tests/test_ki.py

If we have a pending KeyboardInterrupt *and* a pending Cancelled, then
deliver the KeyboardInterrupt.
Rationale: when there are nested cancel scopes, we raise the outermost
Cancelled exception. KeyboardInterrupt is the outerest cancellation.

Rock beats scissors, lizard beats spock, KeyboardInterrupt beats Cancelled

---

docs/source/tutorial.rst

Great tutorial! Thanks for taking the time to write it.

Fixing "already say" -> "already saw" typo.

---

trio/_core/tests/test_run.py

In addition to cluttering up the test output now that pytest collects
and shows warnings, this causes segfaults on some CI builds when run
with -W error (see gh-187).

Hide intentional "coroutine '...' was never awaited" in test suite

---

trio/_core/tests/test_run.py

This is a fixup for 3b831cce397b13b7835bf9384cee75241ee71a73. It turns
out that warning message filters do an *anchored* match, so you have
to write a regexp that matches the beginning of the message. It only
seemed to work because the issue I was trying to fix was intermittent
to start with. Learn something every day...
Before this fix, on 3.5.0 I got a segfault once every ~2-4 runs. After
this fix, I ran 100 times and they all passed.
~/src/cpython/b/install/bin/pytest -W error -v trio -k test_error_in_run_loop --count=100

Fix warnings filter

---

setup.py

Fix some small setup.py issues

---

trio/tests/test_socket.py

test_socket: replace imaginary `ip` protocol with `udp`

---

ci/travis.sh

Like it is today: https://travis-ci.org/python-trio/trio/jobs/242286426

[travis] skip pypy3 nightly when the downloaded tarball is empty

---

trio/_path.py

I noticed this was missing, and it's the only special-case in `Path`, so it probably needs this.

path: add docstring for open

---

trio/_core/tests/test_run.py
trio/_util.py

Otherwise it says it does not have `__enter__` which is obvious for
advanced pythonista. Still a tiny bit clearer is likely better.
I guess this _might_ fool static type checkers, but I'm unaware of any
that would flag that.

Clearer error message if async context manager used synchronously

---

trio/_core/tests/test_run.py
trio/_core/tests/tutil.py
trio/tests/test_ssl.py

This commit
- Fixes the problem (by ignoring BrokenPipeError after receiving a
close_notify, necessary because of our decision in 8b0a252e463 to
close the socket immediately after sending close_notify).
- Changes how we run the server thread so that errors can't pass
unnoticed in the future, but will instead propagate back into the
main thread.

The echo server thread in test_ssl had unnoticed errors

---

trio/_core/tests/test_multierror.py

The reason the tests "freeze" on AppVeyor should have been that
`exec_lines` runs the lines at IPython startup and then leaves the
python shell open, meaning that the process would never exit.  This
should no longer be the case with `code_to_run`, so remove the skip
marker as well.

test_multierror: Use IPython's code_to_run instead of exec_lines

---

trio/_core/_run.py

The previous example had a small thinko and asserted the lock wasn't locked when in fact we had just acquired it.
Fix the example, and add a couple of assertions about lock ownership to attempt to clarify things a little.
Fixes #224 but doesn't attempt to find a simpler example to use instead.

Correct the example in wait_all_tasks_blocked

---

trio/_util.py
trio/tests/test_util.py

Cherry-pick 647438fa5a7b9a5fb3fd1af57541b52646c7a013,
bpo-29692: contextlib.contextmanager may incorrectly unchain RuntimeError
Fixes #203

Port fixes for unchaining exceptions in contextmanager from cpython

---

docs/source/conf.py
docs/source/reference-core.rst
trio/_sync.py
trio/_threads.py
trio/tests/test_sync.py
trio/tests/test_threads.py

You can pass a Semaphore here to avoid overwhelming the system with
too many simultaneous threads.

Implement capacity limitation for run_in_worker_thread

---

trio/_core/_run.py
trio/_core/tests/test_run.py

Cancel scopes used to jump through hoops to make sure that if you had
some code like:
```python
with open_cancel_scope as cs:
cs.cancel()
try:
await sleep(1)
except Cancelled as exc1:
try:
await sleep(1)
except Cancelled as exc2:
assert exc1 is exc2
```
then not only did both of the sleep() calls raise a Cancelled
exception, but they both raised *the same exception object* (i.e., the
assertion above passed). This was motivated by some idea that it would
lead to more complete tracebacks, but in fact I think it just makes
tracebacks more confusing, plus creates nasty things like `__context__`
loops (in the above example, `exc2.__context__ is exc1 is exc2`), plus
it's just surprising if you're used to how things are done in Python
normally.
This commit drops that code; now each sleep() gets …

Stop interning Cancelled exceptions

---

docs/source/conf.py
docs/source/local_customization.py
docs/source/reference-core.rst
docs/source/reference-io.rst
trio/_network.py
trio/socket.py
trio/tests/test_socket.py

This is in preparation for #170.
The PR also gives a slightly better way to document hidden classes
like this.

Hide the trio.socket.SocketType class

---

docs/source/reference-io.rst
trio/_network.py
trio/socket.py
trio/tests/test_socket.py

There were some underscored attributes that were accessed from
SocketStream. Fix that, in preparation for gh-170.

Remove quasi-public APIs from trio socket interface

---

docs/source/reference-io.rst
trio/__init__.py
trio/_open_tcp_stream.py
trio/_ssl_stream_helpers.py
trio/ssl.py
trio/tests/conftest.py
trio/tests/test_open_tcp_stream.py
trio/tests/test_ssl_helpers.py

Not tested, not integrated, just want to get it off my laptop.

Implement happy eyeballs

---

docs/source/reference-io.rst
trio/_network.py
trio/_streams.py
trio/abc.py
trio/ssl.py
trio/testing.py
trio/tests/test_abc.py
trio/tests/test_open_tcp_stream.py
trio/tests/test_ssl.py
trio/tests/test_ssl_helpers.py
trio/tests/test_streams.py
trio/tests/test_testing.py

There was a weird redundancy where there were 3 ways to close things:
- forceful_close: ungraceful, non-blocking, sync
- graceful_close: graceful, potentially blocking, async
- cancelled graceful_close: ungraceful, non-block, async
This is one too many, and we can't really simplify the graceful_close
semantics further, and async file objects can implement all of
graceful_close but *can't* really implement forceful_close (because
even their forceful_close can block momentarily to do some disk
I/O). Async generators ditto. So this commit:
- drops forceful_close
- renames graceful_close to aclose
- adds trio.aclose_forcefully as a convenience function for the cases
where you might have wanted forceful_close
Closes gh-260

We have too many ways to close things; remove the redundancy

---

trio/tests/test_util.py

Stop acontextmanager coverage from flapping all the time

---

docs/source/reference-io.rst

Document that the socket sendall method is not task-safe

---

trio/_highlevel_socket.py
trio/_ssl.py
trio/_util.py
trio/testing/_memory_streams.py
trio/tests/test_ssl.py
trio/tests/test_util.py

Just rename it and make it always do ResourceBusyError, since that's
how it's always used.
Fixes gh-197

Refactor UnLock -> ConflictDetector

---

docs/source/_static/hackrtd.css
docs/source/reference-core.rst
docs/source/reference-hazmat.rst
docs/source/reference-io.rst
trio/__init__.py
trio/_core/_traps.py
trio/_deprecate.py
trio/_file_io.py
trio/_highlevel_socket.py
trio/_path.py
trio/_socket.py
trio/_sync.py
trio/_threads.py
trio/tests/test_deprecate.py
trio/tests/test_socket.py
trio/tests/test_ssl.py
trio/tests/test_threads.py

`trio.socket`'s `sendall` method is deprecated in favor of the new
high-level interface (see #291)
`trio.run_in_worker_thread` is renamed to
`trio.run_sync_in_worker_thread` (see #68), with the old name retained
for now as a deprecated alias.

Add deprecation framework, and do some deprecations

---

.travis.yml
ci/travis.sh
docs/source/reference-core.rst
trio/_core/_run.py
trio/_core/tests/conftest.py
trio/_core/tests/test_run.py
trio/tests/test_ssl.py

start_soon is just a new name for spawn, except it doesn't return the
new task (in preparation for gh-136, where we're going to stop
emphasizing task objects in the main api)
start is a major new feature: it provides a very simple way to start
up a long running task, while blocking until it's finished whatever
initialization it wants to do. At least... it's simple from the user's
point of view. Internally it's quite tricky indeed. The whole _run.py
file probably needs some refactoring and splitting up, but this is one
of those cases where I think it's best to first get the new
functionality working and nailed down, and then we can see what shape
the new abstractions should be.
Fixes gh-284.

Add nursery.start and nursery.start_soon

---

trio/_core/_parking_lot.py
trio/_core/_run.py

Faster ParkingLot

---

trio/_deprecate.py
trio/tests/module_with_deprecations.py

This isn't really needed currently (we'd know, the symptom is a
RecursionError at import time), but it's a genuine bug fix for a
problem I ran into while implementing gh-316. And since that PR seems
to be stalled at the moment, I want to get this in so it doesn't get
forgotten.

Avoid infinite recursion in ModuleWithDeprecations.__getattr__

---

docs/source/design.rst
docs/source/history.rst
trio/__init__.py
trio/_core/__init__.py
trio/_core/_io_epoll.py
trio/_core/_io_kqueue.py
trio/_core/_io_windows.py
trio/_core/_ki.py
trio/_core/_local.py
trio/_core/_parking_lot.py
trio/_core/_result.py
trio/_core/_run.py
trio/_core/_traps.py
trio/_core/_unbounded_queue.py
trio/_deprecate.py
trio/_toplevel_core_reexports.py
trio/hazmat.py
trio/tests/module_with_deprecations.py
trio/tests/test_exports.py

In particular, this should make it so PyCharm's completion starts
working.
Fixes gh-314.

Make our exports more visible to static analysis

---

trio/_deprecate.py
trio/_sync.py
trio/tests/test_deprecate.py
trio/tests/test_sync.py

Deprecate Queue.join and Queue.task_done

---

docs/source/history.rst
docs/source/reference-io.rst
trio/_abc.py
trio/_highlevel_socket.py
trio/_socket.py
trio/socket.py
trio/tests/test_highlevel_open_tcp_listeners.py
trio/tests/test_highlevel_open_tcp_stream.py
trio/tests/test_highlevel_socket.py
trio/tests/test_socket.py

As pointed out in:
https://github.com/python-trio/trio/issues/170#issuecomment-327025129
there are advantages to having the "is this a trio socket" check be
spelled using 'isinstance'. This commit un-deprecates the
trio.socket.SocketType name and makes it an abstract class that
concrete socket implementations should inherit from, and then gets rid
of is_trio_socket since it's now unnecessary.

Remove is_trio_socket

---

docs/source/history.rst
docs/source/reference-core.rst
docs/source/reference-hazmat.rst
trio/__init__.py
trio/_core/__init__.py
trio/_core/_entry_queue.py
trio/_core/_run.py
trio/_core/tests/test_ki.py
trio/_core/tests/test_run.py
trio/_signals.py
trio/_threads.py
trio/_util.py
trio/hazmat.py
trio/testing/_mock_clock.py
trio/tests/test_signals.py
trio/tests/test_threads.py
trio/tests/test_util.py

Adds:
- trio.hazmat.TrioToken
- trio.BlockingTrioToken
Deprecates:
- current_call_soon_thread_and_signal_safe
- run_in_trio_thread
- await_in_trio_thread
The new API has more consistent naming is generally less confusing due
to the use of actual objects instead of the unconventional returning
closures thing.

Renames and deprecations for #68

---

trio/_core/_parking_lot.py
trio/_core/_result.py
trio/_core/_run.py
trio/_core/tests/test_result.py
trio/_core/tests/test_run.py
trio/_highlevel_generic.py
trio/_sync.py
trio/_threads.py
trio/testing/_sequencer.py
trio/tests/test_sync.py

Hopefully we can switch back to using slots=True at some point because
the memory savings are nice, but currently it breaks
weakrefs (gh-331), and currently the supposed workaround breaks on
pypy:
https://github.com/python-attrs/attrs/issues/174#issuecomment-333335667
(See also gh-337 for an abortive attempt to apply that workaround.)
Fixes gh-331

Stop using slots=True in public classes to fix weakref issues

---

trio/_core/tests/tutil.py
trio/tests/test_highlevel_open_tcp_listeners.py
trio/tests/test_socket.py
trio/tests/test_testing.py

IPv6 is not available on all travis images. This will skip IPv6 tests when IPv6 is not available.

Skip tests that need IPv6 if it is not available

---

docs/source/reference-core.rst
trio/_core/_multierror.py
trio/_core/tests/test_multierror.py
trio/_toplevel_core_reexports.py

This monkey patches `traceback.TracebackException` on import. It overrides `TracebackException.__init__()` to extract any inner exceptions from `MultiError`s and overrides `TracebackException.format()` to include the details of the embedded exceptions.
This deprecates `trio.format_exception` as it is no longer needed and is now an alias for `traceback.format_exception`.
Documentation is included detailing some examples where this would be useful e.g. logging.
See gh-305.

Monkey patch traceback.TracebackException to support MultiError

---

trio/testing/__init__.py
trio/testing/_checkpoints.py
trio/tests/test_testing.py

This was deprecated as part of gh-157 due to lack of use cases, but
gh-329 reported a plausible use-case so let's put it back.

Un-deprecate assert_no_yields and rename to assert_no_checkpoints

---

trio/tests/test_timeouts.py

Our tests that sleep actually sleeps for the specified time started
failing on Travis's MacOS builds -- we were requesting to sleep for
0.05 seconds, and woke up after ~0.11 seconds, which is a large enough
overrun to break our tests. The problems started happening without any
changes to our code, so pretty sure this is a Travis issue, not a Trio
issue.
Still, I guess we need to make these tests more robust. The approach
used here is to bump up the sleep time massively from 0.05 seconds to
1.00 seconds, and then mark the relevant tests as @slow. This adds ~5
seconds to the --run-slow test suite, which is something like a 50%
increase on my laptop (but proportionally less if gathering coverage
etc). We can try bumping the number down again later if we need to
speed things up.

Attempt to fix MacOS failures on travis by increasing sleep lengths

---

test-requirements.txt

pytest says:
pytest-catchlog plugin has been merged into the core, please remove it from your requirements.
I hear and obey.

Drop pytest-catchlog from test-requirements.txt

---

trio/tests/test_timeouts.py

This failure:
https://ci.appveyor.com/project/njsmith/trio/build/1.0.768/job/3lbdyxl63q3h9s21
appears to be due to some floating point wackiness causing a >=
assertion to not *quite* succeed. See comment for more details.

Attempt to fix a flaky test on Windows

---

trio/_core/_run.py
trio/_core/tests/test_run.py

Previously the cancel scope repr looked like:
```
CancelScope(_tasks={<Task '__main__.main' at 0x7f7f6af99a90>}, _effective_deadline=228508.69968805768, _deadline=228508.69968805768, _shield=False, cancel_called=False, cancelled_caught=False)
```
This reveals a bunch of internal details. Let's hide those.
Maybe an even nicer version would print some details about the public
attributes like deadline, shield, cancel_called? I hit this while
preparing a talk for Friday though so I want to get this in now :-)

Give cancel scopes a nicer opaque repr

---

docs/source/design.rst

@graydon informs me that Erlang does have exceptions [0]. Whoops. Rephrase
to avoid claiming otherwise otherwise.
[0] http://erlang.org/doc/reference_manual/errors.html

Tweak wording to avoid accidentally slandering Erlang

---

trio/tests/test_ssl.py

This shouldn't happen, but apparently it does sometimes.

Ignore SSLWantWriteError from SSLSocket.unwrap

---

docs/source/reference-core.rst
trio/__init__.py
trio/_core/_run.py
trio/_core/tests/test_run.py
trio/_highlevel_open_tcp_listeners.py
trio/_highlevel_serve_listeners.py
trio/_highlevel_ssl_helpers.py
trio/_toplevel_core_reexports.py
trio/tests/test_highlevel_serve_listeners.py

The asymmetry in task_status=trio.STATUS_IGNORED is bugging me too much. I
gotta change it.
What to change it to? task_status=trio.TASK_STATUS_IGNORED is kind of
long -- 36 characters -- and likely to make 80-character lines wrap.
But the old one was 31 characters, which is already likely to make
80-character lines wrap, and I haven't had any better ideas.
I don't want to make it status=STATUS_IGNORED, because then we're
claiming the kwarg "status" in every Trio server function, which seems
just a little too generic. task_status is more unique and I think
better for attaching this special convention to.
I thought about task_status=NO_TASK_STATUS, but that feels weird. It's
not that the task has no status, it's that the caller is ignoring that
status. I guess we could switch to something …

Rename STATUS_IGNORED to TASK_STATUS_IGNORED

---

trio/_abc.py

This note is important also for the high-level API. Assuming people will
skip the low-level documentation, it seems appropriate to repeat the
note.

Copy note about cancellation from sendall to send_all

---

trio/_util.py
trio/tests/test_util.py

Pretty routine stuff, but I think this gets trio._util to 100% coverage.

Better test coverage for @acontextmanager

---

docs/source/reference-io.rst
docs/source/tutorial/echo-server-low-level.py
newsfragments/241.removal.rst
newsfragments/377.feature.rst
newsfragments/377.removal.rst
notes-to-self/measure-listen-backlog.py
trio/_highlevel_open_tcp_listeners.py
trio/_socket.py
trio/tests/test_highlevel_open_tcp_listeners.py
trio/tests/test_highlevel_open_tcp_stream.py
trio/tests/test_highlevel_socket.py
trio/tests/test_socket.py
trio/tests/test_ssl.py
trio/tests/test_testing.py

Fixes #241
I might also fix the issue known as #377 while I'm at it, but posting now to see
what CI says.

Make socket bind async, and related fixups

---

docs/source/reference-core.rst
docs/source/tutorial.rst
newsfragments/136.feature.rst
notes-to-self/loopy.py
trio/_core/_run.py
trio/_core/tests/test_run.py
trio/_toplevel_core_reexports.py
trio/hazmat.py
trio/testing/_memory_streams.py
trio/tests/test_ssl.py
trio/tests/test_testing.py

- Parenting is no longer a full time job
- This commit also removes a bunch of deprecated functions
Fixes: gh-136

Simplified nurseries

---

trio/_sync.py

Hello!
I found a typo as I was reading the docs. Here is a fix.

Fix typo in `CapacityLimiter.acquire_on_behalf_of_nowait` docstring

---

docs/source/design.rst

Issue #23 was closed as a duplicate of #265.
Have the docs link to the open issue.

Correct issue link in design docs

---

docs/source/reference-testing/across-realtime.py
docs/source/tutorial.rst
notes-to-self/proxy-benchmarks.py
notes-to-self/schedule-timing.py
trio/_core/tests/test_ki.py

The in test_ki.py actually managed to cause a spurious test failure:
https://ci.cryptography.io/blue/organizations/jenkins/python-trio%2Ftrio/detail/PR-389/1/pipeline
so might as well get better habits.

Be more careful about using time.monotonic instead of time.time

---

docs/source/reference-io.rst
newsfragments/1.removal.rst
trio/__init__.py
trio/_core/_multierror.py
trio/_core/tests/test_multierror.py
trio/_highlevel_socket.py
trio/_socket.py
trio/_sync.py
trio/_threads.py
trio/_toplevel_core_reexports.py
trio/testing/__init__.py
trio/tests/test_highlevel_socket.py
trio/tests/test_socket.py
trio/tests/test_sync.py
trio/tests/test_threads.py

Closes #68, #321, #317, #157, #291.

Remove everything else that was deprecated in 0.2.0

---

README.rst
docs/source/_templates/layout.html
docs/source/tutorial.rst

See #402; `trio` is too generic a name to be a suitable tag on Stack Overflow.

Update tag name

---

docs/source/reference-io.rst
newsfragments/401.feature.rst
trio/__init__.py
trio/_core/_ki.py
trio/_core/_run.py
trio/_core/tests/test_run.py
trio/_highlevel_open_unix_stream.py
trio/_highlevel_socket.py
trio/_socket.py
trio/_ssl.py
trio/_util.py
trio/testing/_checkpoints.py
trio/tests/test_exports.py
trio/tests/test_highlevel_open_unix_stream.py
trio/tests/test_ssl.py

A month later, I finally found the motivation to implement this.
Implementation was relatively simple; I reused SocketStream and wrote a very basic connector function (for client connections, I don't think there's any more that could be done).
Note:
- Some of the changes are apparently due to yapf reformatting, and were unintentional.
- The new test uses raw `socket.socket` to emulate a UDS server - not sure if that's the right thing to do.

Unix client socket support. See: #279

---

ci/rtd-requirements.txt
ci/travis.sh
trio/_core/_run.py
trio/_core/tests/test_result.py
trio/_core/tests/test_run.py

We currently have 3 independent problems breaking CI, so we need to
fix them all at once to unwedge things. This PR fixes:
- A bug in how we handle broken pypy3 nightlies (gh-433)
- Some small bugs in our test suite on py37-dev (gh-432)
- Pins our sphinx version at something <1.7.0, as a temporary
workaround for https://github.com/sphinx-doc/sphinx/issues/4609

Combined PR to fix CI

---

trio/_core/_run.py
trio/_core/tests/test_result.py
trio/_core/tests/test_run.py

Travis tests are currently failing because they finally updated their
Python 3.7-dev to something recent, and this created some mild test
breakage. This PR fixes it to get our CI working again.

Python 3.7 fixups

---

ci/travis.sh

We were calling 'exit 0' to skip the tests... inside subshell
parentheses (), so it was only exiting the subshell, not the overall
script. Whoops. Fix that.

[travis] Fix pypy skipping logic

---

docs/source/reference-core.rst

replacement for gh-430, to work around:
https://github.com/python-trio/trio/pull/430#issuecomment-365477421

DOC: Order cancel_called after cancelled_caught

---

trio/_core/tests/test_local.py

We used to use a single queue to send messages to and from the
threads, which of course is unreliable because the main thread could
end up reading back its own message. In particular, on PyPy this
happened regularly, and occasionally it meant that the test
deadlocked. So this fixed gh-379.
This patch also updates the test harness to actually pull errors back
from the child threads, so that if the test does fail then we can
detect it.

Rework test_run_local_simultaneous_runs to be more reliable

---

ci/rtd-requirements.txt
docs/source/conf.py

- Make the fixes suggested here so our docs become compatible with
sphinx 1.7.0:
https://github.com/sphinx-doc/sphinx/issues/4609#issuecomment-365301990
- Upgrade to sphinx 1.7.0

Update to sphinx >= 1.7.0

---

docs/source/reference-core.rst

I assume the intended object was the freshly created 'combined_limiter'

The combined limiter example stores and returns undefined 'limiter'

---

trio/tests/test_highlevel_open_unix_stream.py

The main substantive change here is switching to using mktemp() to
pick a server socket name, instead of using the fixed name
"/tmp/test.sock". This should fix gh-447.
While I was at it, I also refactored the main test, and made it clean
up after itself more carefully.
Finally, I replaced
os.path.join(tempfile.gettempdir(), tempfile.mktemp())
with
tempfile.mktemp()
Because it turns out they're equivalent: mktemp() already returns an
absolute filename inside an appropriate directory.

Refactor open_unix_stream tests, and use more unique filename

---

docs/source/reference-hazmat.rst
newsfragments/452.feature.rst
trio/_core/_run.py
trio/_core/tests/test_run.py
trio/hazmat.py

Re-opened because I broke my fork whilst rebasing.

Add `current_root_task` to get the root task without having to walk the tree.

---

docs/source/tutorial.rst

- Fix outdated "no HTTP library yet" comment
- Fix typo (s/mean time/meantime)

more small tutorial fixes (take 2)

---

newsfragments/342.removal.rst
trio/_core/_exceptions.py
trio/_core/_run.py
trio/_core/tests/test_run.py

Resolves #342.
- Is `RuntimeError` the correct type?
- Should the error message be more helpful? We probably want to point people to `CancelScope.cancel()`

Error for user-created Cancelled()

---

trio/_abc.py

documentation typo - formatting only

---

docs/source/reference-core.rst
newsfragments/473.feature.rst
trio/_sync.py
trio/tests/test_sync.py

Based on ideas and code by @njsmith (#272). Made a PR out of it to discuss API.

New faster Queue with capacity >= 0

---

README.rst

It is nice to see the latest release directly in a badge, plus the conda-forge one lets users know that `trio` can be used with conda.

Add badges for PyPI and conda-forge versions to README

---

trio/tests/test_highlevel_open_tcp_listeners.py

The point of this test is to ask trio to create sockets with two
different backlogs, and then check that they actually have different
backlogs, to make sure that trio is paying attention to our request.
But the two ranges we checked for overlapped, so that it was
theoretically possible that if the backlog was always exactly 10, then
the test could pass, even if trio was ignoring the backlog argument
entirely.
This is not very likely but I noticed it while I was in here fixing
gh-522 and it bugs me.

Tweak backlog test to be slightly more strict

---

Jenkinsfile

pip doesn't respect XDG_CACHE_HOME on MacOS; use PIP_CACHE_DIR instead

---

docs/source/conf.py

Fixing `pygments_style` according to https://github.com/rtfd/sphinx_rtd_theme/issues/633#issuecomment-387594617

fix pygments style in docs

---

.gitignore
trio/_highlevel_socket.py
trio/_socket.py
trio/tests/test_socket.py

Resolves https://github.com/python-trio/trio/issues/422
I'm not sure if the test is correct so please let me know if that (or anything else) needs to be modified.

make SocketType.type match what it will be in python 3.7+

---

trio/_util.py

Just happened to notice the Python 3.5.2 check could be moved out of every aiter_compat-decorated function call. In case it's worth it!

Factor Python 3.5.2 check out of aiter_compat implementation

---

notes-to-self/blocking-read-hack.py
notes-to-self/ntp-example.py

blocking-read-hack.py: This demonstrates a really weird approach to
solving gh-174. See:
https://github.com/python-trio/trio/issues/174#issuecomment-389745133
ntp-example.py: A fully-worked example of using UDP from Trio,
inspired by
https://github.com/python-trio/trio/issues/472#issuecomment-390499565
This should move into the tutorial eventually.

Add two more notes-to-self files

---

trio/_core/_run.py
trio/_core/tests/test_run.py

Alert the user that that passing an async generator to a task spawning method is not allowed.
Fixes #546
I wasn't sure where to add a test for this as it doesn't seem the slew of `TypeError`s and corresponding messages are verified anywhere?

Raise a more explicit async generator error

---

trio/_core/_run.py

This is not currently a problem, but fixing it makes it *obviously* safe and avoids future bugs.  Closes #514.

Use immutable default for argument

---

trio/_sync.py
trio/tests/test_sync.py

When queue.get() is cancelled, the task must not be left on the queue.
Otherwise an interesting crash will result when the next item is pushed.
Best demonstrated by:
```
with trio.move_on_after(0.01) as timeout_scope:
await q.get()
assert timeout_scope.cancelled_caught
await q.put("Test for PR #553")
```

Always force tasks off the queue

---

trio/_sync.py
trio/tests/test_sync.py

This is a follow-up to https://github.com/python-trio/trio/pull/553
The problem is that in the no-error case the task has already been removed, so the `.pop()` will always return its default anyway.

queue.get: Speed up the "no error" case

---

.travis.yml

- Use xenial on GCE for 3.7+
- Add 3.7 and 3.8-dev
I changed `pypy3.5-5.10.1` to `pypy3.5` (which happens to be 5.10.1 just now). Is there a reason it was pinned? The Travis PyPy documentation isn't clear on this.

Test Python 3.7 on Travis

---

.travis.yml
Jenkinsfile
ci/travis.sh

Travis MacOS is much more functional than it used to be, and on
ci.cryptography.org we're hitting:
https://github.com/MagicStack/immutables/issues/7
So let's try turning on Travis's MacOS and see how it goes, while
scaling back our Jenkins testing so that bug doesn't block everything.

Enable MacOS testing on Travis, disable 3.6 testing on Jenkins

---

trio/_ssl.py

Trying to make `SSLListener` doc complete, which is referred to #540 .

complete SSLListener doc

---

newsfragments/548.bugfix.rst
trio/_sync.py
trio/tests/test_sync.py

Fix CapacityLimiter memory leak.

---

.travis.yml
Jenkinsfile
test-requirements.txt

While the Travis MacOS infrastructure is clearly *much* better than it
used to be, doing these tests on Jenkins is still faster overall, and
it avoids hitting gh-584.
This commit:
- adds a temporary workaround for
https://github.com/MagicStack/immutables/issues/7
- re-enables all MacOS builds on Jenkins
- including 3.7, which was previously not enabled
- re-disables Travis MacOS builds

Switch back to Jenkins for MacOS builds

---

test-requirements.txt

The latest release of contextvars (v2.3) fixed this bug, so we don't
need a workaround anymore:
https://github.com/MagicStack/immutables/issues/7

Remove workaround for now-fixed 'immutables' bug

---

trio/_core/_run.py

This should never happen in normal use, but sometimes there are bugs
that can cause the init task to crash. (For example, I hit this while
trying to debug gh-550.) Previously, this would trigger an assertion
failure, and the original exception would be lost. Let's preserve the
original exception to make debugging easier.

Give more details when the init task crashes

---

newsfragments/580.bugfix.rst
trio/_socket.py
trio/tests/test_socket.py

Closes gh-580
@sorcio: This is an unusual bug in that we actually do not know which
systems are affected or why, and we don't have any of the affected
systems in our CI setup. So even if the tests pass here I have no idea
if it's actually working :-). Can you test this branch and confirm it
fixes the failure you were seeing?

Skip a test on systems with buggy AI_V4MAPPED handling

---

trio/_highlevel_open_tcp_listeners.py

As discussed https://gitter.im/python-trio/general?at=5b702354a6af14730b25304e this is a small patch to example code in a doc string.

Fix variable names in docstring example for serve_tcp

---

docs/source/reference-hazmat.rst
newsfragments/400.feature.rst
trio/_core/__init__.py
trio/_core/_io_windows.py
trio/_core/tests/test_io.py

wait_socket_*, notify_socket_close now accept raw socket descriptors

---

ci/travis.sh

Our workaround for gh-508 seems to be working reliably now, so no need
to keep spamming test logs with this.

[ci] Make pip less verbose again

---

newsfragments/612.bugfix.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

avoid use of `@asynccontextmanager` and `@async_generator` since they cause bugs as well as extraneous exception stack frames
TODO:

implement open_nursery with explicit context manager

---

README.rst
docs/source/contributing.rst
docs/source/design.rst
docs/source/history.rst
docs/source/index.rst
notes-to-self/socketpair-buffering.py
setup.py
trio/_core/_wakeup_socketpair.py
trio/_core/tests/test_run.py
trio/_highlevel_open_tcp_listeners.py
trio/_highlevel_socket.py
trio/_signals.py
trio/_socket.py
trio/tests/test_highlevel_socket.py
trio/tests/test_socket.py
trio/tests/test_ssl.py
trio/tests/test_testing.py
trio/tests/test_timeouts.py

https://en.wikipedia.org/wiki/MacOS
We fixed illumos, so hey, why not fix this one too? The only occurrence I left untouched is in setup.py because the PyPI classifier still uses the old name: https://pypi.org/search/?c=Operating+System+%3A%3A+MacOS+%3A%3A+MacOS+X.

Rename MacOS to macOS

---

docs/source/reference-io.rst
newsfragments/354.feature.rst
newsfragments/354.removal.rst
trio/_core/_entry_queue.py
trio/_core/_run.py
trio/_signals.py
trio/tests/test_signals.py

Fixes gh-354
Other changes:
- deprecate trio.catch_signal
- fix a few small edge-cases I noticed along the way

New signal API: trio.open_signal_receiver

---

trio/_sync.py

Make it more clear that trio.Event is level-triggered, and give a hint at how to make it behave as edge-triggered.

trio.Event docs

---

newsfragments/633.bugfix.rst
trio/_highlevel_open_tcp_stream.py
trio/tests/test_highlevel_open_tcp_stream.py

open_tcp_stream can take `host` as either bytes or str, but the formatting for the error message when a host is not found depends on host being a string. When trying to connect to a non-existent host, if passed as a string I would get the exception:
OSError: all attempts to connect to localhost:8081 failed
but when passed as bytes I would get the exception:
if ":" in host:
TypeError: a bytes-like object is required, not 'str'
This PR adds a single line to convert bytes to a string before running the rest of the function (and some tests).

Fix error messages for host not found when `host` is passed in as bytes

---

trio/_core/_run.py
trio/_core/tests/test_run.py

Elide task.context.run() and contextvars.callable() frames from tracebacks

---

trio/_core/_run.py

This is kind of ridiculous overkill, but I was thinking about how you
could do it, then wrote some code to experiment, then realized that
I had implemented it so we might as well use it...

At startup, count how many frames Context.run adds to tracebacks

---

newsfragments/56.feature.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

For #56:
* _nested_child_finished() returns rather than raises MultiError
* implement explicit context manager for CancelScope rather than @contextmanager
* propagate exceptions from cancel scope to nursery `__aexit__` manually
TODO:

Reduce extraneous exception frames

---

trio/_core/_run.py
trio/_core/tests/test_run.py

This is going to be easiest to review as individual commits.
- Reworks how exceptions pass through run() to remove 3 frames from
every trio traceback
- Makes the remaining traceback frames for nursery __aexit__ and
cancel scope __exit__ easier to understand out of context.
- Cleans up some confusing terminology in _run.py
No newsfragment because this is a followup to #640 and that PR's
newsfragment covers these changes too.
Relevant bug: #56

A few more small cleanups to tracebacks

---

appveyor.yml
ci/travis.sh
test-requirements.txt

Maybe this will solve gh-646? Let's find out.

[ci] Try skipping 'coverage combine' with new pytest-cov

---

test-requirements.txt

Due to this error we pin the pytest version to 3.7.4 to get CI to pass.
```
============================= test session starts ==============================
platform darwin -- Python 3.5.3, pytest-3.8.0, py-1.6.0, pluggy-0.7.1 -- /Users/jenkins/workspace/-594-SV5AYVYYLSFPHE6/trio/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/jenkins/workspace/-594-SV5AYVYYLSFPHE6/trio, inifile:
plugins: faulthandler-1.5.0, cov-2.6.0
collecting ... collected 434 items / 1 errors
==================================== ERRORS ====================================
ERROR collecting .venv/lib/python3.5/site-packages/trio/_core/tests/test_multierror.py
../.venv/lib/python3.5/site-packages/trio/_core/tests/test_multierror.py:584: in <module>
import IPython …
```

Pinned pytest version to 3.7.4

---

newsfragments/542.bugfix.rst
newsfragments/542.feature.rst

In the heat of the coding this had been forgotten.

added newsfragment for issue 592 / 542

---

test-requirements.txt
trio/_core/tests/test_multierror.py

And unpin pytest again, since the pin in gh-650 was just a temporary
fix.
Fixes gh-651.

Filter out DeprecationWarning on IPython import in test suite

---

trio/_core/_ki.py
trio/_core/_multierror.py
trio/_core/_run.py
trio/_core/tests/test_multierror.py
trio/_deprecate.py
trio/_socket.py
trio/_ssl.py
trio/testing/_checkpoints.py
trio/tests/test_signals.py
trio/tests/test_ssl.py

I'm going in small stages to make review (and debugging) manageable, so:
- Internally get names as attributes of the stdlib `ssl` and `socket` modules, rather than by magic
- Remove a bunch of unused imports (mostly leftover from deleted code)
- Minor cleanups I found in the process

Another increment for static analysis

---

docs/source/history.rst

Link to the tracebacks blog post
Clean up some text that got mangled when towncrier reflowed it.

Tweak v0.7.0 release notes

---

check.sh
ci/travis.sh
test-requirements.in
test-requirements.txt
trio/_core/_io_epoll.py
trio/_core/_run.py
trio/_core/tests/test_ki.py
trio/_core/tests/test_multierror.py
trio/_core/tests/test_run.py
trio/_core/tests/test_unbounded_queue.py
trio/_path.py
trio/_ssl.py
trio/_util.py
trio/_wait_for_object.py
trio/testing/_check_streams.py
trio/tests/test_path.py
trio/tests/test_socket.py
trio/tests/test_ssl.py
trio/tests/test_sync.py

This catches a whole pile of things that `yapf` doesn't, from trailing whitespace to unused variables or dodgy comparisons.  I've gone for a mixed strategy for existing issues - fixing or suppressing the less common issues so we'll catch any new instances, but globally ignoring a few pervasive lint errors where e.g. `flake8` and `yapf` disagree to favor the latter.
Of course all the import-related issues are behind the `--ignore=` flag, but we'll get #542 eventually!
Finally, I've split out the static analysis job into a new script `check.sh` which can be run locally for quick feedback.  This is also designed to make adding more analysis tools - e.g. `mypy` or `bandit` - as easy as possible.

Run flake8 in CI, split out check script

---

test-requirements.txt
trio/_core/tests/test_run.py

In this PR:
https://github.com/python/cpython/pull/9415
asyncio.sleep switched to requiring a running asyncio event loop. This
is all very sensible, but broke our test that checks what happens when
some accidentally yields an asyncio.Future to the Trio run loop.
Switch the test to waiting on a Future directly.

Don't use asyncio.sleep as a function that waits on an asyncio.Future

---

trio/_core/_ki.py
trio/_highlevel_serve_listeners.py
trio/_ssl.py
trio/_sync.py

Some strings contain content that needs these strings now to be raw strings.
This PR fixes this.

Fixes 'invalid escape sequence \s' deprecation warning on python 3.7

---

trio/_core/tests/test_multierror.py

Now that 7.0 is out, these shouldn't be needed anymore.
*Are* they needed though? Well, let's find out...

Remove warning filters needed for ipython 6.5

---

docs/source/reference-core.rst
docs/source/reference-testing/across-realtime.py
docs/source/tutorial.rst
newsfragments/33.feature.rst
notes-to-self/file-read-latency.py
notes-to-self/proxy-benchmarks.py
notes-to-self/schedule-timing.py
notes-to-self/wakeup-fd-racer.py
trio/_core/_run.py
trio/_core/tests/test_ki.py
trio/_core/tests/test_run.py
trio/testing/_mock_clock.py
trio/tests/test_testing.py
trio/tests/test_timeouts.py

Per the discussion in issue #33 this changes the clock to use time.perf_counter() rather than time.monotonic() on all platforms.

Change to high-resolution clock per #33

---

docs/source/history.rst
docs/source/reference-core.rst
docs/source/reference-hazmat.rst
docs/source/reference-io.rst
docs/source/tutorial.rst
newsfragments/620.removal.rst
trio/__init__.py
trio/_abc.py
trio/_core/__init__.py
trio/_core/_exceptions.py
trio/_core/_io_epoll.py
trio/_core/_io_kqueue.py
trio/_core/_io_windows.py
trio/_core/tests/test_io.py
trio/_highlevel_generic.py
trio/_highlevel_socket.py
trio/_ssl.py
trio/_subprocess/unix_pipes.py
trio/_util.py
trio/testing/_check_streams.py
trio/testing/_memory_streams.py
trio/tests/test_highlevel_ssl_helpers.py
trio/tests/test_signals.py
trio/tests/test_ssl.py
trio/tests/test_testing.py
trio/tests/test_util.py

- Rename BrokenStreamError to BrokenResourceError
- Rename ResourceBusyError to BusyResourceError
Fixes gh-620 (and see there for the rationale).

Rationalize generic exception names

---

docs/source/tutorial.rst

Code had string 'Woke up after ' but the corrosponding output had 'Woke up again after '

Fixed a typo in tutorial.rst

---

docs/source/reference-io.rst

On top of that, I'm not sure about the single `\r\n` sequence finishing the http requests
Considering the following code:
```python
import trio
import sys
async def test():
ssl_context = trio.ssl.create_default_context()
raw_stream = await trio.open_tcp_stream('example.com', 443)
print('Opened:', raw_stream)
cooked_stream = trio.ssl.SSLStream(raw_stream, ssl_context, server_hostname='example.com')
await cooked_stream.send_all(b"GET /index.html HTTP/1.0\r\n")
if '--double-lf' in sys.argv:
await cooked_stream.send_all(b"\r\n")
print('waiting answer...')
ret = await cooked_stream.receive_some(100)
print(ret)
trio.run(test)
```
I'm getting a timeout if I'm not using a double `\r\n`
```shell
$ python test_stapledSSL.py 
Opened: <trio.SocketStream object at 0x7fc31cfa10f0>
waiting answer... …
```

Correct example in reference-io.rst

---

trio/_channel.py

In particular, make clear that memory channels don't serialize their
objects, since that was raised as a point of confusion in chat.
Also reword some stuff

Small improvements to open_memory_channel docs

---

docs/source/reference-core.rst

One of those issues was spotted by @sorcio: https://github.com/python-trio/trio/pull/586#discussion_r222959728.

docs: fix Sphinx errors in Channel docs

---

trio/_core/tests/test_ki.py

Fix for #624 
:wave: So I ran trio's tests using the projects `test-requirements.txt` and all seems well there. I am developing on OSX, so I didn't actually get to run the tests in a windows environment. 
As a side note I got this warning running pytest:
```
(venv) [12:11 PM] ~/code/trio-learn/trio $ pytest                                                                                                                                    
================================================================================ test session starts ================================================================================
platform darwin -- Python 3.7.0, pytest-3.8.2, py-1.6.0, pluggy-0.7.1 …
```

Increase sleep time to account for clock differences

---

.travis.yml
appveyor.yml

We only use dependabot. Or at least I think so? I don't know how to check that. So this pull request is my way of asking the question.

ci: remove unneeded pyup references

---

docs/source/reference-hazmat.rst
newsfragments/649.feature.rst
trio/_core/__init__.py
trio/_core/_run.py
trio/_core/_traps.py
trio/_core/tests/test_run.py
trio/hazmat.py

I'm not sure if this is a good idea, but I guess we'll give it a try
and see how it goes.
Closes gh-649.

Support handing off coroutines between Trio and other runners

---

newsfragments/618.feature.rst
trio/_sync.py
trio/_wait_for_object.py
trio/tests/test_sync.py

Looking to make my first (small) contribution to trio with a "good first issue" (https://github.com/python-trio/trio/issues/618)

Allow CapacityLimiter(math.inf)

---

trio/_abc.py
trio/abc.py

We continue to work towards making the code easier for static analysis tools.

Migrate trio.abc from star import to explicit imports, to aid static analysis

---

trio/socket.py
trio/tests/test_exports.py

This switches to a single parametrized test that covers all of Trio's
public namespaces, and if it fails, then it prints a nice readable
list of the missing symbols.
Also adds the symbols that were missing from trio.socket's static
import list on my laptop, and adds some comments to trio.socket while
I'm at it.
CC: @jmfrank63 @Zac-HD

Generalize namespace static analysis tests

---

newsfragments/609.bugfix.rst
trio/_highlevel_socket.py
trio/tests/test_highlevel_open_tcp_stream.py
trio/tests/test_highlevel_socket.py

Fixes #609.
I have a few questions:
- What should I do about this test which fails without the getpeername check? https://github.com/wgwz/trio/blob/wgwz/fix-for-609/trio/tests/test_highlevel_socket.py#L27-L30 I'm thinking it might be that the test just doesn't matter anymore. 
- What type of a newsfragment should I use? I'm guessing bugfix or removal..

Removes call to getpeername in SocketStream

---

trio/hazmat.py
trio/tests/test_exports.py

Continuing towards finalisation of #542 
We do a try / except import of our symbols to aid static analysis tools to pick them up. Then we update the list dynamically to have python get the correct symbols.

Migrate hazmat to faked explicit importing and reexporting, to aid static analysis (issue #542)

---

newsfragments/809.bugfix.rst
trio/_highlevel_open_tcp_stream.py
trio/_highlevel_open_unix_stream.py
trio/tests/test_highlevel_open_tcp_stream.py
trio/tests/test_highlevel_open_unix_stream.py

improve handling of `open_tcp_stream` in the case of errors/exceptions being thrown.  previously it looked like there were a few places the code could be interrupted and it would end up leaking file descriptors
I've changed it to track everything in `open_sockets`, and only have a single winner.
I started writing this along with [Nathaniel's PyCon 2018](https://www.youtube.com/watch?v=oLkfnc_UMcE) talk but ended up structuring the retry behaviour differently as I found his confusing to follow.  Not sure if my code will catch all the cases appropriately or is actually better, hence the WIP.
Comments appreciated!

improve error handling in open_tcp_stream

---

docs/source/reference-core.rst

This pull request fixes the invalid link to the documentation for Open Tracing.

Fix invalid documentation link for opentracing.io

---

trio/_core/_run.py

This allows test helpers etc. to reproduce scheduling-dependent heisenbugs by seeding the `Random` instance.  (or at least ensures that *something else* will prevent reproductions instead)
I have draft patches against `pytest-trio` and Hypothesis to take advantage of this, but since this has no observable impact except to enable those future patches I thought this was a good place to start.

Use module-level Random to shuffle tasks

---

newsfragments/853.bugfix.rst
trio/_core/tests/tutil.py
trio/_highlevel_open_tcp_listeners.py
trio/tests/test_highlevel_open_tcp_listeners.py
trio/tests/test_socket.py
trio/tests/test_testing.py

Closes #853.
- Some such systems return both address families from `getaddrinfo` but fail with `EAFNOSUPPORT` in `socket`. Allow `open_tcp_listeners()` to ignore `EAFNOSUPPORT` as long as at least one listener is created successfully.
- Fix socket tests to be more careful about not even trying to create an IPv6 socket on systems that don't support IPv6.

Improve support for systems with IPv4 or IPv6 administratively disabled

---

newsfragments/862.feature.rst
trio/_subprocess.py
trio/tests/test_subprocess.py

This is intended to make it more ergonomic to speak a back-and-forth protocol with a subprocess.

Add Process.stdio as a convenience StapledStream of stdin and stdout

---

appveyor.yml
ci/travis.sh

See: https://docs.codecov.io/docs/flags
When we get bizarro coverage results (e.g. complaints about comments
not executing), then I'm hoping this will help us track them down.

Enable codecov flag support

---

ci/travis.sh

It currently doesn't work:
https://bitbucket.org/pypy/pypy/issues/2943/
and has been the cause of much confusion. Hopefully we can re-enable
it again later.

Disable coverage reporting on pypy's py3.6 nightly branch

---

docs/source/reference-io.rst
newsfragments/863.feature.rst
trio/_subprocess.py
trio/tests/test_subprocess.py

On POSIX, don't permit two error-prone combinations that the underlying `subprocess` module supports:
* string command with `shell=False`: user might think it word-splits somehow, but actually it treats the entire string as the name of an executable to invoke with no arguments
* list command with `shell=True`: binds the extra arguments to shell variables `$1`, `$2`, etc, instead of passing them to the command being executed
Add a section on quoting to the subprocess documentation, explaining the above restrictions and acquainting users with the many pitfalls of using `shell=True` on Windows.

Subprocess support: tighten and document expectations for how the command is specified

---

newsfragments/661.bugfix.rst
newsfragments/874.bugfix.rst
trio/_highlevel_socket.py
trio/_unix_pipes.py
trio/testing/_check_streams.py
trio/tests/test_unix_pipes.py

This addresses a number of issues:
- Fixes a major issue where `aclose()` called `notify_fd_close()`
unconditionally, even if the fd was closed; if the fd had already
been recycled this could (and did) affect unrelated file
descriptors:
https://github.com/python-trio/trio/issues/661#issuecomment-456582356
- Fixes a theoretical issue (not yet observed in the wild) where a
poorly timed close could fail to be noticed by other tasks (gh-661)
- Adds `ConflictDetector`s to catch attempts to use the same stream from
multiple tasks simultaneously
- Switches from inheritance to composition (gh-830)
Still todo:

Rewrite unix pipe fd handling logic

---

newsfragments/890.feature.rst
trio/_core/_run.py
trio/tests/test_scheduler_determinism.py

See python-trio/pytest-trio#73 - this is important for Hypothesis, and arguably for debugging in general.  
I've used the current time as primary sort key, with name and task cancel/schedule points to order tasks that started at the same time according to perf_counter.  This is all deterministic, and any remaining collisions are probably coming from random bitflips.
I've also designed the tests to be imported into pytest-trio's test suite, and the Hypothesis test added.

Support deterministic scheduling

---

trio/_core/tests/test_multierror.py

Until https://github.com/ipython/ipython/issues/11590 is fixed.

Mark failing IPython multierror tests as xfail on 3.8

---

newsfragments/860.bugfix.rst
trio/_core/_exceptions.py
trio/_core/_run.py
trio/_core/tests/test_run.py
trio/tests/test_highlevel_open_tcp_stream.py

Delay deciding which cancel scope a Cancelled exception belongs to

---

newsfragments/320.misc.rst
trio/_core/_run.py
trio/_core/tests/test_run.py
trio/_core/tests/tutil.py

Fixes #320. Now that #901 is implemented, the concerns discussed in #835 don't apply.

Cancel a cancel scope upon entry if its deadline is in the past

---

trio/_core/_run.py
trio/_core/tests/test_run.py

To keep our options open for adding a smarter `was_cancelled` property, per discussion in #886.

Disable cancel scope reuse

---

.travis.yml

See https://bitbucket.org/cffi/cffi/issues/403/build-fails-on-38-dev-pyinterpreterstate for details.

Skip 3.8-dev as cffi build fails

---

.travis.yml
ci/ci.sh
test-requirements.txt

This reverts commit 678878e2b15c55b9e6e0f38e9a7ab908b4fcb7e6. cffi has been released with a temporary fix, it should work on 3.8-dev from now on.

Revert "Skip 3.8-dev as cffi build fails"

---

ci/ci.sh
setup.cfg
trio/_core/tests/test_multierror.py

I only noticed this issue when looking at an unrelated 3.8-dev failure (which is now fixed). So I also configured pytest to fail any passing xfail test.
Now that we no longer have xfail tests, how do you convince yourself that xfail_strict works? You can:
* run `pytest trio --run-slow` without the first commit
* look at https://travis-ci.org/pquentin/trio/jobs/521670563 which fails because it only contains the xfail_strict change.
Also, in all builds pytest now mentions the `setup.cfg` file like this:
```
rootdir: /home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/trio, inifile: setup.cfg
```

 Remove xfail now that IPython tests pass on 3.8

---

test-requirements.in
test-requirements.txt
trio/_core/tests/test_multierror.py
trio/_core/tests/test_run.py
trio/tests/test_highlevel_ssl_helpers.py
trio/tests/test_socket.py

yapf 0.27.0 introduce some formatting changes. We should apply them to make #995 happy.
I added a couple `# yapf: disable` because I thought the code as is is more readable.
I don't quite like the lines starting with `) =` but that's my own opinion.
Example of suggested change were:
```patch
--- trio/tests/test_socket.py   (original)                                                                                                                                                                                                     
+++ trio/tests/test_socket.py   (reformatted)        
@@ -471,20 +471,20 @@                                                   
async def res(*args):                                                    
return await getattr(sock, resolver)(*args)
-        assert await …
```

fix formatting with yapf 0.27.0 (should make #995 happy)

---

docs/source/reference-core.rst

As stated in #1008, The doc was not clear about the fact that CancelScopes are not meant to be reusable.

CancelScopes are not meant to be reusable anymore (fix #1008)

---

docs/source/reference-core.rst

Regarding this issue: #1009
I'm not sure if it's too emphasized, though. It looks like this:
And I couldn't get reStructuredText to do a code block *inside* a warning using just indentation (like it's done in the rest of the docs). I had to add the prefix `.. code-block:: python`.

Add a warning about return statements in nurseries

---

newsfragments/917.bugfix.rst
trio/_path.py
trio/tests/test_path.py

Partially resolves issue #917 by conditionally generating wrappers
for pathlib.Path methods that return iterators.
This commit can also handle generating ``Path.iterdir`` but the docstring referencing issue #501 would have to be accounted for.

[WIP] Generate pathlib.Path iterator methods

---

notes-to-self/how-does-windows-so-reuseaddr-work.py
notes-to-self/print-task-tree.py

- Add the test script used in gh-928 to decipher Window's port reuse
semantics
- Note the existence of the 'tree-format' package (found thanks to
@itamarst)

Add some more notes to self

---

newsfragments/1005.bugfix.rst
trio/_core/_multierror.py
trio/_core/tests/test_multierror.py

This PR refers to #767 and #1005 in order to allow unhashable exceptions in `MultiError`s.
There is still a limitation though, you need to run python > 3.6.4 because `MultiError` relies on `traceback.TracebackException` which gained the support of unhashable Exceptions in 3.6.4.

Exceptions don't need to be hashable (see #767 and #1005)

---

docs-requirements.in
test-requirements.in

Hopefully this will resolve #1034. I tested with `pip-compile` on 3.7 and we do get the `cpython` restriction on typed-ast + inclusion of `immutables` in the output.

Fix each requirements.in to generate correct requirements.txt even when run on 3.7

---

newsfragments/1021.misc.rst
trio/_core/_exceptions.py
trio/_core/_run.py
trio/_core/tests/test_run.py
trio/_util.py
trio/tests/test_util.py

Issue: #1021 
Added two new metaclasses:
1. `Final`: Ensures that no class can inherit the class using the metaclass
2. `NoPublicConstructor`: Ensures that no object of the class using the metaclass can be directly created. This metaclass derives from `Final`, also ensuring 1

Enforce private instantiation and inheritance through metaclass

---

docs/source/reference-core.rst

Add missing "trio." to move_on_after call.

Fix shield code example

---

newsfragments/1066.feature.rst
trio/_core/_multierror.py
trio/_core/tests/test_multierror.py

add MultiError.__init__ to avoid linter confusion

---

.travis.yml

The "pypy3.5" tag points to pypy3.5 v5.10, while we actually want to
test against the latest pypy3 release, which is pypy3.6 v7.1. For now
at least the "pypy3" tag seems to be up to date, so let's use that and
cross our fingers that it stays that way.
We were also still testing against the pypy3.5 branch nightlies, even
though that branch is now abandoned in favor of the pypy3.6 branch. We
were already testing against pypy3.6 nightlies, so we can just drop
the pypy3.5 nightlies.

Update pypy versions in travis

---

newsfragments/882.feature.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

When exiting an outer cancel scope before some inner cancel scope nested inside it, Trio would previously raise a confusing chain of internal errors. One common source of this misbehavior was an async generator that yielded within a cancel scope. Now the mis-nesting condition will be noticed and in many cases the user will receive a single RuntimeError with a useful traceback. This is a best-effort feature, and it's still possible to fool Trio if you try hard enough, such as by closing a nursery's cancel scope from within some child task of the nursery.
Fixes #882. Relevant to #1056, #264.

Attempt to recover from cancel scope nesting violations

---

docs/source/design.rst
docs/source/reference-core.rst
docs/source/reference-hazmat.rst
newsfragments/474.misc.rst
trio/_core/_io_epoll.py
trio/_core/_io_kqueue.py
trio/_core/_io_windows.py
trio/_core/_run.py
trio/_core/_unbounded_queue.py
trio/_core/tests/test_io.py
trio/_highlevel_socket.py
trio/_signals.py
trio/_socket.py
trio/_ssl.py
trio/_sync.py
trio/_timeouts.py
trio/_unix_pipes.py
trio/_util.py
trio/_windows_pipes.py
trio/testing/_checkpoints.py
trio/testing/_memory_streams.py
trio/tests/test_socket.py
trio/tests/test_ssl.py
trio/tests/test_sync.py
trio/tests/test_util.py

Stop requiring an async operation that raises an exception to act as a checkpoint

---

trio/tests/test_timeouts.py

As per njsmith's sugguestion in #1081. This should close issue #1081.
_Background_
This is an "arbitrary fudge factor" that gives an upper bound on when waiting for an async function to finish. Sometimes this upper bound proves too low, such as in [this CI build](https://dev.azure.com/python-trio/trio/_build/results?buildId=598&view=logs) where a test finished in 1.39 seconds, failing the build. To mitigate this, the factor has been increased to 50%.

[Sleep-time-leniency] Increase threshold to 50%

---

docs/source/conf.py
docs/source/history.rst
docs/source/reference-core.rst
trio/_file_io.py
trio/_highlevel_open_tcp_stream.py
trio/_ssl.py

Issue #78
Set default_role to obj and refactored out existing :obj: tags. Fixed 3 sphinx warnings for unresolved references and spot checked the docs. I did NOT look at all the defaults being parsed by sphinx, so it's possible some of them have silently changed meaning. I guess the way to check this would be to diff the html output and make sure it's small?

Refactor to default role obj

---

newsfragments/637.removal.rst
trio/_signals.py
trio/_sync.py
trio/tests/test_sync.py

Deprecate Event.clear()

---

docs/source/history.rst
docs/source/reference-core.rst
docs/source/reference-core/blocking-trio-portal-example.py
docs/source/reference-hazmat.rst
docs/source/reference-io.rst
newsfragments/810.removal.rst
notes-to-self/blocking-read-hack.py
notes-to-self/thread-dispatch-bench.py
trio/__init__.py
trio/_core/_entry_queue.py
trio/_core/_traps.py
trio/_core/tests/test_run.py
trio/_file_io.py
trio/_path.py
trio/_socket.py
trio/_subprocess_platform/waitid.py
trio/_sync.py
trio/_threads.py
trio/_wait_for_object.py
trio/tests/test_signals.py
trio/tests/test_ssl.py
trio/tests/test_threads.py
trio/tests/test_util.py
trio/tests/test_wait_for_object.py

Rename run_sync_in_worker_thread -> run_sync_in_thread

---

newsfragments/928.misc.rst
trio/_highlevel_open_tcp_listeners.py
trio/tests/test_highlevel_open_tcp_listeners.py

Tiny change to stop setting SO_EXCLUSIVEADDRUSE on sockets before binding them in trio.open_tcp_listeners when on win32, per all the messy details in issues 39, 72 and 928.

Drop usage of SO_EXCLUSIVEADDRUSE on win32 (#928)

---

docs/source/reference-io.rst
newsfragments/1109.removal.rst
trio/__init__.py
trio/_subprocess.py
trio/tests/test_subprocess.py

Add trio.open_process, and deprecate Process(...)

---

docs/source/reference-core.rst
docs/source/reference-io.rst
newsfragments/719.feature.rst
trio/__init__.py
trio/_abc.py
trio/_channel.py
trio/_util.py
trio/abc.py

Make MemorySendChannel and MemoryReceiveChannel into public classes,
and move a number of the methods that used to be on the abstract
SendChannel/ReceiveChannel interfaces into the Memory*Channel concrete
classes. Also add a Channel type, analogous to Stream.
See: gh-719
Still to do:
- Merge MemorySendChannel and MemoryReceiveChannel into a single
MemoryChannel
- decide what to do about clone
- decide whether to add some kind of half-close on Channel
- ~~refactor this PR's one-off solution to gh-1092 into something more
general.~~ done

Refactor channel interfaces

---

docs/source/reference-io.rst
newsfragments/760.feature.rst
trio/_socket.py
trio/tests/test_socket.py

As explained in #760, this PR adds a new `is_readable` method to `trio.socket.SocketType` object.

add a new is_readable method to SocketType (fix #760)

---

docs/source/reference-hazmat.rst
newsfragments/829.feature.rst
trio/_subprocess.py
trio/_subprocess_platform/__init__.py
trio/_unix_pipes.py
trio/hazmat.py
trio/tests/test_unix_pipes.py

add hazmat.FdStream

---

docs/source/reference-io.rst
docs/source/tutorial.rst
docs/source/tutorial/echo-client.py
docs/source/tutorial/echo-server.py
newsfragments/959.feature.rst
notes-to-self/graceful-shutdown-idea.py
trio/_abc.py
trio/_highlevel_generic.py
trio/_highlevel_socket.py
trio/_ssl.py
trio/_subprocess.py
trio/_unix_pipes.py
trio/_windows_pipes.py
trio/testing/_check_streams.py
trio/testing/_memory_streams.py
trio/tests/test_highlevel_generic.py
trio/tests/test_ssl.py
trio/tests/test_subprocess.py
trio/tests/test_testing.py

This came out of discussion in gh-959

Streams are iterable + receive_some doesn't require an explicit size

---

docs/source/history.rst
docs/source/reference-core.rst
docs/source/reference-core/from-thread-example.py
docs/source/reference-hazmat.rst
docs/source/reference-io.rst
newsfragments/810.removal.rst
notes-to-self/blocking-read-hack.py
notes-to-self/thread-dispatch-bench.py
trio/__init__.py
trio/_core/_entry_queue.py
trio/_core/_traps.py
trio/_core/tests/test_run.py
trio/_file_io.py
trio/_path.py
trio/_socket.py
trio/_subprocess_platform/waitid.py
trio/_sync.py
trio/_threads.py
trio/_wait_for_object.py
trio/from_thread.py
trio/tests/test_signals.py
trio/tests/test_ssl.py
trio/tests/test_threads.py
trio/tests/test_util.py
trio/tests/test_wait_for_object.py
trio/to_thread.py

For consistency with trio.from_thread, and to give us a place for
future extensions, like utilities for pushing context managers into
threads.
See gh-810.

Add new trio.to_thread module for running worker threads

---

docs/source/history.rst
newsfragments/1167.bugfix.rst
trio/__init__.py
trio/tests/test_threads.py

When it was deprecated in gh-1122, it accidentally got moved into
trio.hazmat.
Fixes: gh-1167

Put BlockingTrioPortal back where it's supposed to be.

---

newsfragments/819.bugfix.rst
trio/_ssl.py
trio/tests/test_highlevel_ssl_helpers.py
trio/tests/test_ssl.py

Workaround OpenSSL 1.1.1 session-ticket issue

---

trio/_core/tests/test_run.py

This test has been the source of a few intermittent failures recently:
https://github.com/python-trio/trio/issues/200#issuecomment-515667567
Not really clear if this will solve the problem, but it's worth a try.

Use a longer sleep in test_run::test_timekeeping

---

newsfragments/1175.bugfix.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

This could happen in practice if a `finally:` block set an inner scope to be
shielded while a cancellation targeting the outer scope was propagating.
(Or if a user used private APIs to raise `Cancelled` directly themselves,
which is how it was first discovered.)
Fixes #1175.

Prevent uncancelled scopes from catching Cancelled exceptions

---

newsfragments/810.bugfix.rst
trio/_util.py
trio/tests/test_util.py

In particular, this fixes the deprecation warning for
trio.run_sync_in_worker_thread.

Fix __name__ and __qualname__ of trio.to_thread.run_sync

---

README.rst

I recently switched the default docs version on RTD from 'latest' to
'stable', because people kept getting confused by reading about future
features that weren't released yet. But the README was still linking
directly to the 'latest' version.

Update README to point to stable docs instead of dev docs

---

newsfragments/552.bugfix.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

This improves debuggability (since the traceback points to the location of the error, rather than just the nursery whose task was at fault) and fixes #552 by ensuring we don't abandon the child tasks of the errant one.

Recover from a 'foreign await' by throwing in the TypeError

---

docs/source/reference-core.rst

- Typo in function passed to `run_sync`
- It looks like the example predates the dropping of kwargs, so limiter wasn't actually ever being passed

Fix minor issues in CombinedLimiter example

---

newsfragments/1191.bugfix.rst
newsfragments/550.bugfix.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

Don't crash on C coroutine objects

---

newsfragments/1190.bugfix.rst
trio/testing/_mock_clock.py

Ensure MockClock autojump never feed jump with negative values

---

.readthedocs.yml

Closes #1030
You can see the build here: https://readthedocs.org/projects/trio-pquentin/builds/9737603/result and the result here: https://trio-pquentin.readthedocs.io/en/rtd-v2-format/ (nothing changes!).

docs: migrate to v2 Read the Docs format

---

ci.sh

Set --connect-timeout when running curl, to make --retry work, and hopefully fix #1231

---

docs/source/contributing.rst

In `contributing.rst`, the instructions for running tests locally appear to have been cut-and-pasted from the pytest manual, or something like that, and it's not clear exactly what to type.  Replacing "project" with "trio" in two places fixes this.  In particular, I have verified that `pytest trio` is the correct command to run the test suite once everything is set up.
Also use a code-block instead of a bulleted list of verbatim strings.

Make testing instructions less generic

---

newsfragments/1259.bugfix.rst
trio/_path.py
trio/tests/test_path.py

See https://github.com/python-trio/trio/issues/1259
New Behavior:
- `hash(Path("foo/bar/baz")) == hash(Path("foo/bar/baz"))`
- `hash(trio.Path("foo/bar/baz")) == hash(pathlib.Path("foo/bar/baz"))`

Fix Path's hash behavior to match `pathlib.Path`'s

---

newsfragments/1235.bugfix.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

This will probably never come up in real life, but I hit it while
messing around with some microbenchmarks, and the fix is easy.

Don't crash when CancelScopes are nested *very* deeply

---

newsfragments/109.bugfix.rst
trio/_core/_io_windows.py
trio/_core/_run.py
trio/_core/_wakeup_socketpair.py
trio/_core/tests/test_ki.py
trio/_util.py

Also switched signal_raise to always run the C-level signal handler in
the current thread, which gives us more control over signal delivery
and lets us test the new behavior.
Fixes gh-109

Move set_wakeup_fd into common code, used on all platforms

---

docs/source/reference-core.rst

The link at line 272 was dead, I've updated it.

Update link in timeout note (docs)

---

.travis.yml
azure-pipelines.yml
ci.sh

I'm not sure if this is actually useful... I just got curious about it
today and it came together more easily than I expected, so now I'm
curious if it actually works :-).
Rumor says that Travis supports nested KVM acceleration now, if you're
using their 'bionic' image, so in theory this should work and be
reasonably fast?
Right now, it isn't especially useful. But if we started adding
support for new Linux kernel features like pidfd (#1241) or
io_uring (#932), then this would become important, because AFAICT this
is the only way to run tests on new kernels on any of the hosted CI
services.
I guess we could also use it to like, test on ARM or something, if we
cared? I experimented with testing on 32-bit, but the test setup
failed because cryptography has stopped shipping 32-bit wheels, …

[wip] [ci] Run tests in a full-fledged ubuntu 19.10 VM

---

trio/tests/test_ssl.py

Work around openssl Connection(Reset|Aborted)Error on Windows

---

azure-pipelines.yml

The Azure folks are claiming that the 3.8 rollout is "close enough" (https://github.com/microsoft/azure-pipelines-image-generation/issues/1317), so let's give it a try.

Test on macOS + CPython 3.8

---

.travis.yml
azure-pipelines.yml

Only Travis has Python dev builds, an up-to-date pypy build, or nested
virtualization. But we can at least move the more generic stuff over
to Azure to take advantage of the higher parallelization.

[ci] Attempt to speed up CI by moving more jobs from Travis → Azure

---

docs/source/tutorial.rst

> Hey, on the tutorial: it says: "it’s baked into Trio’s design that you never have two tasks running at the same time. " and then right after: "Trio can run 10,000+ tasks simultaneously without breaking a sweat". That's a bit confusing.
> that could use some better wording, yeah
> the same event loop will never run two tasks simultaneously
> but it can run a vast number of tasks concurrently
> yeah, they mean "same time" slightly differently, but that phrasing is confusing for sure... any chance you're up for making a PR to make it clearer?
I kinda don't still get it but I'm opening the PR to get the balling rolling.

Attempt to clarify "same time" wording in tutorial

---

newsfragments/1272.feature.rst
trio/_core/_io_common.py
trio/_core/_io_epoll.py
trio/_core/_io_kqueue.py
trio/_core/_io_windows.py
trio/_core/_run.py
trio/_core/tests/test_io.py

Make Trio more robust to fds/handles being closed behind our back

---

.gitignore
trio/_deprecate.py

This PR improves the error message by specifying the module name and also renames `_deprecate.py --> _check_attrs.py` as it might be somewhat misleading for an actual `AttributeError` to be raised from a module named `_deprecate.py`. This latter change might be controversial?
```python
In [1]: import trio
In [2]: trio.stuff
Traceback (most recent call last):
File "<ipython-input-2-558a186a1b55>", line 1, in <module>
trio.stuff
File "c:\users\dhirschf\code\github\python-trio\trio\trio\_check_attrs.py", line 125, in __getattr__
raise AttributeError(msg)
AttributeError: module 'trio' has no attribute 'stuff'
```

Improve module-level AttributeError message

---

docs/source/awesome-trio-libraries.rst
docs/source/index.rst

Making a page right after the tutorial with some links to libraries that have trio support.

Starting an awesome-trio list

---

ci.sh
trio/_util.py

We now test Python 3.8 on Windows, so I rebased the commits of https://github.com/python-trio/trio/pull/784 on top of master (without using coverage master). I don't know how to configure Azure Pipelines on my fork, so here's a PR. It's only a draft because I first want to see if we see the same things.

Enable Python 3.8 coverage

---

.travis.yml
ci.sh

Upgrading to PyPy 7.2 allows removing the coverage workaround.
I also tried using PyPy 3.7 nightly, but there are a few TLS/SSL errors that I don't understand, so I'll try that in another pull request.

Test PyPy 7.2

---

setup.py

The wheel bug was fixed in 2017 by setuptools. Indeed, the METADATA is correct now.
https://github.com/pypa/wheel/issues/181

Add back cffi on install_requires

---

ci.sh

[The Azure Pipelines bug is now fixed](https://developercommunity.visualstudio.com/content/problem/743824/bash-task-on-windows-suddenly-fails-with-bash-devf.html).

ci: use bash <(curl ...) again

---

azure-pipelines.yml

It's useful to test branches in forks before submitting a pull request.
It also mirrors the Travis configuration.

Run Azure CI on branches too

---

.travis.yml

Until https://travis-ci.community/t/python-development-versions-no-longer-include-pip-due-to-virtualenv-20-x/7180 is fully resolved.
The fix should land in the Travis Python real soon now, but until then let's unblock all the pull requests that are waiting. I'll revert this as soon as I can confirm the fix.
See #1402 for more details.

Allow dev builds to fail

---

trio/_highlevel_open_tcp_listeners.py

Hi,
I just change the message printed when a user passes a string to `open_tcp_listeners`, previously it was said that it can be a *string* which is not true

Update error message in IO function open_tcp_listeners

---

docs/source/reference-core.rst
docs/source/reference-io.rst
docs/source/reference-testing.rst
trio/_abc.py
trio/_core/_generated_run.py
trio/_core/_run.py
trio/_highlevel_open_tcp_stream.py
trio/_highlevel_ssl_helpers.py
trio/_sync.py
trio/testing/_memory_streams.py

Hi folks,
This PR fixes some typos in documentation. I marked it WIP because I want another change but I don't know how to do it. It concerns this section in reference-io
I don't know if is possible to create an alias for a `:ref:` :(

[WIP] Update various errors/typos in rst documentation and docstrings

---

trio/_highlevel_open_unix_stream.py
trio/tests/test_highlevel_open_unix_stream.py

Hi,
this PR fixes an edge case where a user can pass a number when calling `open_unix_socket`. In this case he will get a `TypeError`. There are two possibilities:
- We can just let `socket` function raises the error or
- We can intercept the error and print a nicer message, which is what I did
And in all cases, we need to update the docstring :)

Update function open_unix_socket to check the type of filename argument

---

trio/__init__.py

This is the deprecation warning needed for #1396. I tested that the deprecation warning works as expected locally and it looks good to me:
```
(venv) wgwz@icegarden ~/code/trio $ python
Python 3.5.9+ (heads/3.5:276eb67c29, Feb 19 2020, 11:04:36)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trio
__main__:1: TrioDeprecationWarning: Support for Python 3.5 is deprecated since Trio 0.14; use Python 3.6+ instead (https://github.com/python-trio/trio/issues/75)                            
>>>
```
Running the tests locally worked as expected as well and I now see this warning there too (expected):
```
venv/lib/python3.5/site-packages/py/_path/local.py:701
/home/wgwz/code/trio/venv/lib/python3.5/site-packages/py/_path/local.py:701: …
```

Deprecation warning for python3.5

---

setup.cfg
trio/tests/test_exports.py

This is partly an RFC. I'm not sure if this is exactly the best way to resolve my issue, but I thought a PR would be a good starting point for a discussion.
In Debian, trio packaging can no longer be rebuilt successfully. This is because we run upstream tests as part of the package build, and the upstream tests have started failing. They're failing because `test_exports.py::test_static_tool_sees_all_symbols` fails because Debian has updated Python since I last updated the trio packaging, and `socket.py`'s duplicate list of symbols has fallen behind.
I understand why the test exists, and it makes perfect sense - for upstream. You want CI to fail if the list falls behind, so you can keep it up to date. I'm not sure it makes sense for downstreams that package trio to be running this test …

Mark upstream-only test

---

ci.sh

Apparently this got accidentally disabled as part of a cleanup a while
ago. (The problem is that the bash <(...) syntax assumes that curl is
printing the file to stdout, but we're actually redirecting to a
temporary file in order to handle retries.)

Turn codecov back on

---

docs/source/reference-core.rst

The trio library needs to use `trio.sleep()` instead of regular `sleep` function.

[Fix][Docs] use trio.sleep instead of sleep

---

.github/workflows/ci.yml
trio/_tools/gen_exports.py

Github Actions is probably a better choice anyway, because the free
tier gives us 2x the resources, plus it avoids all the janky stuff
with managing separate Pipelines user accounts. But the final straw is
that Azure Pipelines has been totally broken for unknown reasons for
the last week+, see: #1455, #1466, etc.

Port Azure Pipelines configuration to Github Actions

---

trio/_threads.py

`token` and `trio_token` are the same.
I guess we don't need to pass `trio_token` to the thread function as a arg parameter, but that seems more explicit so I removed `token` instead of removing `trio_token`.

Remove redundent token variables.

---

.github/workflows/ci.yml

By default, as soon as a single job in a group fails, then GA will
cancel all the other jobs. This is kind of confusing, e.g. I was just
looking at a PR that had a Python 3.5-specific failure, but that
wasn't immediately obvious, because GA only ran the 3.5 tests and then
skipped all the others. So let's disable that behavior.

Add fail-fast: false to Github Actions config

---

docs/source/reference-core/from-thread-example.py

When I was reading the docs, I was unsure of why `portal` was there in the reference.
My assumption is that it's there to hint to the reader that calling `trio.to_thread.run_sync` creates a portal in a sense, but based in the function signature the comment was confusing to me.
Please correct me if I'm misunderstanding anything!

Removed reference to `portal` in from thread example

---

newsfragments/1241.feature.rst
trio/_subprocess.py

This is identical to #1296, but for some reason that PR has gotten
into a glitchy state where GH won't let it be merged. So I'm opening a
second PR in hopes that GH will somehow un-wedge themselves.
Fixes #1241

Use pidfd to implement trio.Process.wait, when available (2nd try)

---

newsfragments/1241.feature.rst
trio/_subprocess.py

Fixes #1241
The new QEMU-based CI run (#1292) *should* let us test this. I'm curious
to see what codecov says :-).
But unfortunately, even with that, we're still only testing the
ctypes-based configuration, not the configuration that uses the stdlib
`os.pidfd_open` that currently only exists in CPython master. We're
running tests on CPython master, and we're running tests on a new
kernel, but we aren't doing both at the same time. AFAICT the only way
to test that configuration would be to check out and build CPython
master from inside the nested VM, which sounds like a real hassle.
OTOH, I'm not super comfortable about shipping code that hasn't been
tested... `os.pidfd_open` is pretty simple but it's always possible my
ctypes-based implementation has some subtle behavioral difference I …

Use pidfd to implement trio.Process.wait, when available

---

.github/workflows/ci.yml

We don't really care about this in general, because we run CI on
everything before its merged. But codecov cares, because it needs this
to figure out the "baseline" for coverage comparisons.

Enable GHA CI on pushes to the master branch

---

docs/source/design.rst

This fixes a typo in the docs.

Fix typo in docs: issue 29587 -> issue 29256.

---

setup.py

This allows the installation of trio on Windows + PyPy3.

Prevented the installation of cffi on PyPy

---

newsfragments/1109.feature.rst
newsfragments/1109.removal.rst
trio/_subprocess.py
trio/tests/test_subprocess.py

Remove support for calling trio.Process() directly

---

docs/source/reference-core.rst
newsfragments/1044.removal.rst
trio/_core/_entry_queue.py
trio/_core/_local.py
trio/_core/_parking_lot.py
trio/_core/_run.py
trio/_core/_unbounded_queue.py
trio/_highlevel_generic.py
trio/_highlevel_socket.py
trio/_path.py
trio/_ssl.py
trio/_sync.py
trio/_unix_pipes.py
trio/_util.py
trio/_windows_pipes.py
trio/testing/_memory_streams.py
trio/testing/_mock_clock.py
trio/testing/_sequencer.py
trio/tests/test_exports.py
trio/tests/test_util.py

This changes most of Trio's public classes so that attempts to
subclass them will produce a deprecation warning, with the idea that
once the deprecation period passes on we'll use metaclass=Final to
make subclassing an error.
See #1104 for discussion.
There are some special cases where we do allow subclassing: ABCs,
exceptions, enums, etc. I also added a test to make sure that every
public class is either Final, on its way to becoming Final, or else
falls into one of the special cases. The idea is that when we add new
classes in the future, this will force us to either mark them Final,
or else add a new special case, hopefully with a comment explaining
what makes the new class a special case.

Move towards making most public classes Final

---

trio/_core/tests/test_run.py
trio/_util.py
trio/tests/test_util.py

This is a pretty trivial change, but I noticed it while working on
gh-1496 so I figured I'd just fix it.

Better error messages from Final and NoPublicConstructor

---

.travis.yml
ci.sh

With this change, we'll use Ubuntu 20.04 in most Travis builds, which will allow us to continue testing pidfd, but without using a VM. We'll also use Linux 5.6 with Fedora 32, which will allow to add tests for io_uring in the future. It's not clear yet whether we want to do that now or not, but I wanted to see if it was possible. This is exactly https://github.com/python-trio/trio/pull/1507, but in #1507 GitHub did not see that Travis had succeeded.

Newer Linux kernels in CI

---

newsfragments/1315.feature.rst
trio/_subprocess.py
trio/tests/test_subprocess.py

make trio.Process.returncode automatically update itself as needed

---

.gitignore
trio/_core/_entry_queue.py
trio/_core/_ki.py
trio/_core/_local.py
trio/_core/_multierror.py
trio/_core/_parking_lot.py
trio/_core/_unbounded_queue.py
trio/_file_io.py
trio/_highlevel_open_tcp_listeners.py
trio/_highlevel_open_tcp_stream.py
trio/_highlevel_open_unix_stream.py
trio/_highlevel_serve_listeners.py
trio/_highlevel_socket.py
trio/_highlevel_ssl_helpers.py
trio/_path.py
trio/_signals.py
trio/_socket.py
trio/_sync.py
trio/_timeouts.py
trio/_wait_for_object.py
trio/testing/_check_streams.py
trio/testing/_checkpoints.py
trio/testing/_memory_streams.py
trio/testing/_mock_clock.py
trio/testing/_network.py
trio/testing/_sequencer.py
trio/testing/_trio_test.py

#1500 
In addition, added `pyvenv.cfg` into `.gitignore`

[#1500]: Remove unused __all__ variables from Trio modules

---

.readthedocs.yml
docs/source/conf.py

This has several advantages:
- On RTD, folks using the 'latest' tag to look at the git version of
the docs will be able to see what's changed in git.
- On pull requests, newsfragments will be included in the RTD CI
build, so we have the option of previewing them in rendered form
before merging.
This commit also configures RTD sphinx to fail on warnings, in hopes
that this will make RTD CI work as a replacement for our current doc
CI job.

Automatically run towncrier on RTD for in-development versions

---

docs/source/conf.py
newsfragments/1104.feature.rst
trio/_subprocess.py
trio/tests/test_subprocess.py

And also tweak the default to something a bit nicer on Unix.
Fixes: #1209

Allow customization of run_process cancellation behavior

---

newsfragments/1526.bugfix.rst
trio/_signals.py
trio/tests/test_signals.py

[#1526]: Preventing the problem of catching an empty list of signals

---

ci.sh
newsfragments/1065.bugfix.rst
trio/_core/_multierror.py
trio/_core/tests/test_multierror.py
trio/_core/tests/test_multierror_scripts/apport_excepthook.py

Make Trio's excepthook play nicely with Ubuntu's excepthook

---

docs/source/releasing.rst

Following @njsmith's procedure here: https://gitter.im/python-trio/general?at=5ec36d49940fa238d6fffa33

Simplify releasing documentation

---

docs/source/conf.py

This looks like it will fix our RTD build.

Docs: suppress epub warnings for unknown file types

---

docs/source/history.rst
newsfragments/1244.bugfix.rst
trio/_version.py

The main reason for another release is to get readthedocs to build our "stable" documentation with the fix in #1541. Due to timing, we also get #1513.

Release v0.15.1

---

trio/tests/test_subprocess.py

gh-1514 introduced a race condition in this test: now if the process
runs quickly enough, the returncode might have magically become
non-None before we check it.
Example failure: https://travis-ci.org/github/python-trio/trio/jobs/690291915
There are other tests that check the 'p.returncode is None' case (e.g.
test_auto_update_returncode), so we can just delete this.

Fix flakiness in test_subprocess::test_basic

---

trio/tests/test_subprocess.py

In gh-1546 I fixed the flakiness due to the returncode changing when
the process exits, but I missed that the repr also changes...

Another attempt to fix flakiness in test_subprocess::test_basic

---

test-requirements.in

Now that Dependabot is using 3.8, a requirement only applicable below 3.8 is completely ignored. But black pulls in typed-ast unconditionally, and pip-tools isn't smart enough to propagate environment constraints along dependency edges, so we wind up with typed-ast as an unconditional dependency which makes pypy builds fail. Constraining it in requirements.in based on only the interpreter, not also the Python version, resolves this (tested by running pip-compile on 3.8 directly).

Remove constraint on typed-ast requirement

---

check.sh

`black --diff` doesn't exit with failure if any changes were necessary; you need `black --check` for that.

Actually enforce black formatting

---

docs/source/awesome-trio-libraries.rst

It looks like PyPI now have a specific url for trove serach pattern.
This filter down the result to "only" 3 pages instead of 500.

Update PyPI search link for Framework::Trio

---

.travis.yml

To work around issues like https://github.com/MagicStack/immutables/issues/46

Temporarily disable testing on python nightly

---

trio/_core/tests/test_multierror.py
trio/_highlevel_open_tcp_stream.py
trio/tests/test_highlevel_open_tcp_listeners.py
trio/tests/test_highlevel_socket.py
trio/tests/test_highlevel_ssl_helpers.py
trio/tests/test_socket.py
trio/tests/test_ssl.py

Prompted by this random test failure:
https://github.com/python-trio/trio/issues/200#issuecomment-635919605

Fix a bunch of ResourceWarnings due to leaked fds

---

docs/source/reference-lowlevel.rst
newsfragments/1558.feature.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

This tracks the nursery in which the task is going to run, even if it's not really running there yet because the `start()` that spawned it hasn't returned. Came up in discussion surrounding #1523 but seems independently useful.

Add Task.eventual_parent_nursery introspection attribute

---

docs/source/reference-lowlevel.rst
trio/_core/_ki.py
trio/_core/_run.py
trio/_core/tests/test_ki.py

This is mostly motivated by wanting to allow guest-mode (gh-1551) to
use our KI handling, where the host loop will presumably not be using
any of our KI protection markers. But I figured I'd split it out into
a separate PR rather than mix changes to the tricky KI code together
with changes to the tricky core run loop.
No newsfragment because I don't think this change is observable by
users.

Switch KI protection default from "unprotected" to "protected"

---

trio/tests/test_threads.py

Sometimes ResourceWarnings decide to print during this test, and that
used to cause it to fail every once in a while.

Make test more specific to prevent flakiness

---

trio/tests/test_deprecate.py

Hopefully this will resolve test flakiness in test_deprecated.py, recently discussed in #200.

Ignore ResourceWarnings in test_deprecate

---

trio/_core/_run.py
trio/tests/test_scheduler_determinism.py

I consistently see batch shuffling taking 1% CPU on a real-world
application, and this is a simple fix to make this overhead disappear.
Suggested by @njsmith.

Don't shuffle each batch, instead reverse them half the time.

---

newsfragments/1574.removal.rst
trio/__init__.py
trio/_threads.py
trio/tests/test_exports.py
trio/tests/test_threads.py

Remove deprecated BlockingTrioPortal

---

newsfragments/1573.bugfix.rst
trio/_threads.py
trio/tests/test_threads.py

This functionality was previously added to the `trio.from_thread` functions in #1513
Closes #1573

Added helpful error message if an async function is passed to trio.to_thread_run_sync

---

trio/tests/test_highlevel_open_tcp_listeners.py

Give up on measuring TCP socket backlog

---

newsfragments/1594.deprecated.rst

Add newsfragment for ssl/subprocess removals

---

newsfragments/1587.deprecated.rst
trio/_core/_generated_run.py
trio/_core/_run.py
trio/_core/tests/test_mock_clock.py
trio/tests/test_testing.py

It was only added for the autojump clock, it wasn't very good at that,
and since gh-1588, the autojump clock doesn't even use it anyway.

Deprecate the tiebreaker= argument to wait_all_tasks_blocked

---

trio/_core/tests/test_thread_cache.py

It can lead to confusion, e.g.: https://github.com/python-trio/trio/issues/1604

Stop leaking a thread in test_race_between_idle_exit_and_job_assignment

---

.github/workflows/ci.yml

This is the same configuration that we have in Travis: it allows testing
the CI before sending a pull request.
You can see the CI running on my fork here: https://github.com/pquentin/trio/runs/765167558

Run GitHub Actions in forks too

---

newsfragments/1613.feature.rst
trio/_core/_run.py

This is a bit of a kluge, and will hopefully be cleaned up in the
future when we overhaul KeyboardInterrupt (gh-733) and/or the
cancellation checking APIs (gh-961). But 'checkpoint()' is a common
operation, and this speeds it up by ~7x, so... not bad for a ~4 line
change.
Before this change:
- `await checkpoint()`: ~24k/second
- `await cancel_shielded_checkpoint()`: ~180k/second
After this change:
- `await checkpoint()`: ~170k/second
- `await cancel_shielded_checkpoint()`: ~180k/second
Benchmark script:
```python
import time
import trio
LOOP_SIZE = 1_000_000
async def main():
start = time.monotonic()
for _ in range(LOOP_SIZE):
await trio.lowlevel.checkpoint()
#await trio.lowlevel.cancel_shielded_checkpoint()
end = time.monotonic()
print(f"{LOOP_SIZE / (end - start):.2f} schedules/second") …
```

Make trio.lowlevel.checkpoint much faster

---

newsfragments/1595.feature.rst
trio/_socket.py
trio/tests/test_socket.py

Profiling a user-written DNS microbenchmark in gh-1595 showed that UDP
sendto operations were spending a substantial amount of time in
_resolve_address, which is responsible for resolving any hostname
given in the sendto call. This is weird, since the benchmark wasn't
using hostnames, just a raw IP address.
Surprisingly, it turns out that calling getaddrinfo at all is also
quite expensive, even you give it an already-resolved plain IP address
so there's no work for it to do:
In [1]: import socket
In [2]: %timeit socket.getaddrinfo("127.0.0.1", 80)
5.84 µs ± 53.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [3]: %timeit socket.inet_aton("127.0.0.1")
187 ns ± 1.5 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
I thought getaddrinfo would be effectively free …

Add a fast path for the simplest cases of socket address resolution

---

newsfragments/1621.fix.rst
trio/_core/_io_kqueue.py

This small bug was introduced in gh-1551
Fixes gh-1621

In KqueueIOManager, close the force-wakeup fd

---

newsfragments/1596.deprecated.rst
trio/__init__.py

I still need a news fragment, but I'll wait for #1593 to go through. ~~And I guess I'll add the newsfragment for https://github.com/python-trio/trio/pull/1594 here too.~~

Remove remaining aliases deprecated in 0.12.0

---

docs/source/reference-io.rst

https://trio.readthedocs.io/en/v0.16.0/reference-io.html#asynchronous-filesystem-i-o
Presently the link `jump down to the API overview` resolves to `ref:async-file-io-overview` and triggers an xdg-open confirmation in my browser.

Correct file I/O 'jump down to api' doc link

---

newsfragments/1629.feature.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

Continuation of @Tronic's work in #1351
Main changes:
- Rebased on top of master, resolving a number of conflicts
- Reworked the heap management code in the `Deadlines` class, in particular to ignore defunct deadlines when computing the `next_deadline`.
Using the microbenchmark here: https://github.com/python-trio/trio/pull/1351#issuecomment-581390193
On my laptop I get:
**Current master**
```
❯ ./wrk http://localhost:5000 --latency
Running 10s test @ http://localhost:5000
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   657.76us  284.24us  12.20ms   90.78%
Req/Sec     7.74k     1.11k    8.86k    80.20%
Latency Distribution
50%  616.00us
75%  734.00us
90%    0.85ms
99%    1.28ms
155534 requests in 10.10s, 10.09MB read
Requests/sec:  15399.87 …
```

Switch to heap-based deadline tracking

---

README.rst

The original issue was fixed by GitHub.
See the result here: https://github.com/pquentin/trio/blob/rawgit/README.rst
Closes #1633

Stop using RawGit workaround

---

newsfragments/1638.fix.rst
trio/_core/_thread_cache.py
trio/_core/tests/test_thread_cache.py

Don't hold a reference to the last  job in the thread cache

---

newsfragments/275.feature.rst
trio/_highlevel_open_tcp_stream.py
trio/socket.py
trio/tests/test_highlevel_open_tcp_stream.py

Add local_address= kwarg to open_tcp_stream

---

check.sh
test-requirements.in
test-requirements.txt
trio/_core/__init__.py
trio/_core/_io_epoll.py
trio/_core/_io_kqueue.py
trio/_core/_multierror.py
trio/_core/_run.py
trio/_core/tests/test_multierror.py

This is a less ambitious version of #1254, the idea being that we can introduce mypy cleanliness gradually. I did copy relevant code from #1254, and fixed other issues too.
The relevant message in CI can be found in the [check formatting check](https://github.com/python-trio/trio/pull/1610/checks?check_run_id=764547595):
```
++ mypy -p trio._core --platform linux
Success: no issues found in 45 source files
```

Enforce mypy-cleanliness on trio._core

---

trio/_core/_io_epoll.py
trio/_core/_io_kqueue.py
trio/_core/_io_windows.py

We would like to write:
```
if TYPE_CHECKING:
assert sys.platform == "linux"
```
But that hides the assert to mypy. This commits finds a way to avoid that issue.
We still use platform checks in `trio._core._run` and `trio._core.__init__`. Do we want to avoid them there too?

Only assert platform when type checking

---

.github/workflows/ci.yml
ci.sh

CI: Fetch Komodia-based LSP from a source we control

---

.github/workflows/ci.yml

dependabot opens a branch in the main repository and then opens a pull request, which triggers the same build twice. To avoid that, we had branches-ignore set to ignore the push.
However the syntax was incorrect: since the branch name contains slashes, we have to use two stars to ignore it. See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet for details on that syntax.
(I opened a branch in the main repository to mimick the way dependabot works, that way we'll see if the fix works.)

Ignore dependabot pushes correctly

---

.travis.yml

See https://github.com/pypa/setuptools/issues/2350 for details. pip, setuptools and wheel are the only packages that we don't pin, and indeed the pylint tests started failing with setuptools 50.0 on Python 3.6.1. (No other configuration is affected.)

Fix setuptools 50 import in Python 3.6.1 pylint test

---

trio/_ssl.py
trio/tests/test_ssl.py

There is a small typo in trio/_ssl.py, trio/tests/test_ssl.py.
Should read `renegotiation` rather than `renegotation`.

docs: Fix simple typo, renegotation -> renegotiation

---

setup.py

RawGit has shut down, but GitHub fixed the original issue so it's no longer needed.
This was fixed for the GitHub README in https://github.com/python-trio/trio/pull/1635, but I forgot about PyPI. I just noticed it now as RawGit stopped serving the image.

Stop using RawGit URL in PyPI

---

newsfragments/1726.deprecated.rst
trio/_core/_local.py
trio/_core/_mock_clock.py
trio/_core/_parking_lot.py
trio/_core/_unbounded_queue.py
trio/_highlevel_generic.py
trio/_highlevel_socket.py
trio/_path.py
trio/_ssl.py
trio/_sync.py
trio/_unix_pipes.py
trio/_util.py
trio/testing/_memory_streams.py
trio/testing/_sequencer.py
trio/tests/test_exports.py
trio/tests/test_util.py

It was deprecated in Trio 0.15.0.

Stop allowing subclassing public classes

---

docs/source/tutorial.rst

I misunderstood this section of the tutorial: I thought the "echo client" code provided both server and client. 
So I made it clear in the tutorial that the first code sample (the client) does not work without a server listening on the other end.

clarified the 'Networking with Trio' section of the tutorial

---

newsfragments/1738.bugfix.rst
trio/_core/_generated_run.py
trio/_core/_run.py
trio/_threads.py
trio/tests/test_threads.py

Fixes #1738. Also improve the documentation for spawn_system_task() to more clearly indicate this possibility.
Rationale for RunFinishedError: callers to `from_thread.run()` already need to be able to handle the case where the run is finished, and it's difficult to distinguish "has started async generator finalization" from the case where the run is fully done. I would also entertain other options (raise Cancelled? block until the run actually finishes and then raise RunFinishedError?) if anyone wants to make a case for why a different choice might be more robust.

Make trio.from_thread.run() raise RunFinishedError if the system nursery is closed

---

.travis.yml

This reinstalls/rebuilds packages and stops depending on an old libffi version.
https://forums.freebsd.org/threads/certbot-python3-7-dependency-error.76808/
Failing build, for reference: https://travis-ci.org/github/python-trio/trio/jobs/735639080

Fix FreeBSD build by busting the cache

---

.travis.yml
newsfragments/1765.bugfix.rst
trio/_core/_wakeup_socketpair.py
trio/_core/tests/test_guest_mode.py

Apparently, in pypy, "signal.set_wakeup_fd" doesn't have the keyword argument warn_on_full_buffer.
Here is a simple script to reproduce this problem:
```
import trio
async def handler(stream: trio.abc.Stream):
await stream.receive_some(1)
async def trio_main():
socket_listeners = await trio.serve_tcp(handler)
trio.run(trio_main)
```
The error message is:
```
Traceback (most recent call last):
File "/home/leo/test/triotest/pypyvenv/site-packages/trio/_core/_run.py", line 2030, in unrolled_run
runner.entry_queue.wakeup.wakeup_on_signals()
File "/home/leo/test/triotest/pypyvenv/site-packages/trio/_core/_wakeup_socketpair.py", line 66, in wakeup_on_signals
self.old_wakeup_fd = signal.set_wakeup_fd(fd, warn_on_full_buffer=False)
TypeError: set_wakeup_fd() got an unexpected keyword argument …
```

Fix a crash in pypy.

---

.github/workflows/ci.yml

Apparently the latest one no longer uses an LSP?

Try using an older version of Proxifier

---

docs/source/awesome-trio-libraries.rst

Hi, as proposed by @njsmith [here](https://trio.discourse.group/t/a-webscraping-library-with-trio-pyscalpel/341/2?u=le_woudar)  I want to add my library in the documentation

add pyscalpel to awesome trio libraries

---

newsfragments/1797.feature.rst
trio/_channel.py
trio/tests/test_channel.py

This is part of #719. @njsmith asked whether memory channels should have a sync `.close()` method. @oremanj , @lordmauve and myself have said that this would be useful, and no-one has argued against it (please correct me if I've overlooked it!).
My rationale: it's possible to create memory channels and send/receive using synchronous methods, so it seems odd that you need async code to close them. It also makes clean-up after cancellation more difficult, because `await chan.aclose()` will raise `Cancelled` again, so you either need to ensure nothing runs after it, or shield it as described in [Cancellation semantics](https://trio.readthedocs.io/en/stable/reference-core.html#cancellation-semantics).
I've also included synchronous context manager (`with chan:`) support, as I think that's a …

Synchronous .close() method for memory channels

---

.builds/freebsd.yml

Apparently py38 isn't available in the package repos anymore on our
test machines.

Bump freebsd CI to test on python 3.9

---

newsfragments/1280.bugfix.rst
newsfragments/1832.bugfix.rst
notes-to-self/socket-scaling.py
trio/_core/_io_windows.py
trio/tests/test_socket.py

Fixes #1280. By placing the AFD handle within an `AFDGroup` class that keeps track of the number of associated `AFDPollOp`s and giving each op a reference to its group, we can use a `SortedList` to grab the largest not-full group and therefore AFD handle with a simple pop. The bookkeeping is a little unencapsulated, but the bulk of the changes are inside of `WindowsIOManager._refresh_afd` anyway. 
My own benchmarking showed negligible overhead and an optimal `MAX_AFD_GROUP_SIZE` of 500 to avoid scaling issues but YMMV.

avoid cubic AFD cancellation scaling with AFDGroups

---

.github/workflows/ci.yml
.travis.yml

This is actually different from Travis as we're not testing nightly builds, but alpha versions. Should we use the deadsnakes nightly builds instead?
Also, 3.10 does not work yet, due to https://github.com/benjaminp/six/issues/341.

Test Python development versions in GitHub Actions

---

docs/source/tutorial.rst
docs/source/tutorial/echo-client.py
docs/source/tutorial/echo-server.py
docs/source/tutorial/tasks-with-trace.py

Since the lowest version we're now supporting is Python3.6, I took the liberty to replace the .format() style strings in the tutorial with f-strings for enhanced readability.

Replaced .format() with f-strings in the tutorial examples

---

.github/workflows/ci.yml
.travis.yml

I also dropped the pypy-36 nightly here, b/c I don't think it gives us
much -- new features seem to be happening in py3.7.

Try moving nightly pypy builds off travis

---

docs/source/reference-core.rst

Mention Nursery.cancel_scope in CancelScope docs

---

newsfragments/1558.deprecated.rst
trio/_core/_generated_run.py
trio/_core/_run.py
trio/tests/test_testing.py

Note that we have another `tiebreaker` variable in `self._heap` but I think it's unrelated and still useful.

Remove the deprecated `tiebreaker` argument

---

newsfragments/1770.bugfix.rst
trio/_core/_multierror.py
trio/_core/_run.py
trio/_core/tests/test_run.py

When put together, this change +
https://github.com/python-trio/outcome/pull/29 should fix #1770
Note that the tests on this PR are expected to fail until that fix to
`outcome` lands and has been released, since this PR includes a full
end-to-end test.

Avoid creating reference cycles

---

trio/_timeouts.py

Clarify that deadline in `sleep_until()` uses internal clock units

---

.builds/fedora.yml

I guess previously python3-pip depended on something
that depends on python3-devel (which contains the C headers),
but apparently relying on implicit dependencies is never a good thing.

Update dependencies for Fedora CI

---

newsfragments/1864.bugfix.rst
trio/_core/_run.py
trio/_core/tests/test_run.py

This PR fixes a "bug" where `unrolled_run` hangs on to `Cancelled` tracebacks too long. They essentially persist until the _next_ exception is thrown out of a task, which may be an indefinite period of time. This was not cleaned up with the earlier cyclic garbage bugfix #1770 because it is not cyclic garbage; it's actually a strong reference that lives unnecessarily long.
(Thinking out loud here) This is just the minimum possible fix. There are actually a number of locals akin to `final_outcome` in `unrolled_run` that may live up to `_MAX_TIMEOUT` seconds and contain references to tasks and potentially to hefty objects, but I haven't actually observed any issues along those lines yet. Scattering `del` statements everywhere is probably untenable, but factoring chunks of `unrolled_run` into …

make sure coroutine locals are promptly destroyed

---

notes-to-self/how-does-windows-so-reuseaddr-work.py

- Generate the table headers dynamically.
Prior to this change the table headers were static and incorrect,
'specific' and 'wildcard' labels were reversed.
Example output from before the change (incorrect):
~~~
| default           |
| specific| wildcard|
---------------------
default | wildcard |   INUSE | Success |
default | wildcard | Success |   INUSE |
~~~
Example output from after the change (correct):
~~~
| default             |
| wildcard | specific |
-----------------------
default | wildcard |    INUSE |  Success |
default | wildcard |  Success |    INUSE |
~~~
Bug: https://github.com/python-trio/trio/issues/928#issuecomment-774630606
Closes #xxxx
---
/cc @njsmith

notes-to-self: fix table in how-does-windows-so-reuseaddr-work.py

---

setup.cfg
test-requirements.txt

See #1878 for the initial dependabot PR showing the build issues.
https://docs.pytest.org/en/stable/changelog.html (See 6.2.0 features)
https://docs.pytest.org/en/stable/usage.html#unraisable
I think that disabling these new plugins for now is reasonable since it allows us to keep moving forward with pytest versions while retaining the same lack of these checks as if we held the version back.  If there is concern about globally disabling these checks then I think a follow up ticket and PR would be appropriate.
I did make a cursory effort to use `@pytest.mark.filterwarnings()` but failed to get it to successfully avoid the new errors.  I suspect something related to the combination with `-W error` and other pytest features but I did not dig into it.

Bump to Pytest 6.2.2 with -p no:unraisableexception -p no:threadexception

---

ci.sh
pyproject.toml
setup.cfg
trio/_core/tests/test_asyncgen.py
trio/_core/tests/test_guest_mode.py
trio/_core/tests/test_run.py
trio/_core/tests/test_thread_cache.py
trio/_core/tests/test_windows.py
trio/_core/tests/tutil.py

by restoring the default unraisablehook, and disabling the threading.excepthook in tests that need it

reenable pytest -p unraisableexception and -p threadexception

---

ci.sh

It's now configured in pyproject.toml

remove redundant -W error pytest flag

---

trio/_core/_entry_queue.py
trio/_core/_local.py

to avoid accidentally forgetting the `__weakref__` slot

use attr.s for slotted classes

---

.github/workflows/ci.yml

since we lost the installer binary
Closes #1938

Disable Windows "with IFS LSP" test based on Spyware Doctor AV

---

docs/source/awesome-trio-libraries.rst

The project seem to have no activity since October, and does not work
out of the box when installing:
```
>>> ImportError: cannot import name 'aopen' from 'anyio'
```
It requires anyio ~2.x but is actually failing with it.
As it is the first of the list; it is likely to be tried first and users
wondering if they are doing something wrong (guilty of this myself), or
if trio is broken.

DOC: Demphasize `asks` from awesome libraries (broken)

---

trio/_core/_thread_cache.py

Attempting to address #1958 by moving the code that handles jobs into its own method. This is my first contribution, so let me know if I need to do anything differently. Thanks!

Addresses #1958: Move code that handles job into its own method

---

docs/source/reference-core.rst

When I was first reading through the docs for trio I was a bit thrown off by the use of a memory channel in the race example. Since the memory channel itself is not what is meant to be demonstrated here, I think it might be better to remove it in favor of simple variable assignment. Another plus of this is it demonstrates the ability to use nurseries themselves for waiting. 
I may be alone in being confused with the memory channel, so please let me know if you prefer it the original way, and also let me know if you have any questions about this.
Thanks!

updated race example to use variable assignment to track winner instead of memory channel

---

trio/testing/_check_streams.py
trio/tests/test_socket.py

Add `# pragma: no cover` to a few places where our tests have
fallbacks for OS flakiness, and that are causing coverage to randomly
go up and down depending on CI host load.

Reduce coverage flapping

---

.builds/fedora.yml

I made a small docs-only PR here: https://github.com/python-trio/trio/pull/2036
And it seems there's an issue for the CI with `fedora.yml`: https://builds.sr.ht/~njs/job/525148
It's about building the wheel for `cffi` from source, so, not really relevant to the original docs PR.
🤞 ~This PR is to try to debug it and hopefully fix it.~  It seems this PR fixes it. 🎉 
---
Fedora Rawhide (the development version) comes with Python 3.10 by default: `3.10.0~b2-3.fc35`
But `cffi` has built wheels for up to Python 3.9.
I see from the logs of CI runs for recent PRs that up to recently it was using Python 3.9, so I suspect it's fine to pin it to 3.9 for now, while there are built wheels for `cffi` for Python 3.10.

👷  Debug and hopefully fix a CI issue with Fedora

---

docs/source/tutorial.rst

:memo: Add small description of "call stack" in tutorial.
---
Thanks for building Trio! I love how beginner-friendly the tutorial is, it makes me feel that I'm learning and that I'm welcome.
In the same spirit, I realized the first mention of "call stack" doesn't have an explanation about what it is.
I think it might not be obvious, and given there's a great explanation above about async context managers, I thought this could be relevant too.

📝  Add small description of call stack in tutorial

---

docs/source/tutorial.rst

✏️  Fix a couple of typos in tutorial.
Also change the word "trace" that is more technical and probably not necessary (or could deserve an explanation) to the word "point", which is simpler to understand for newcomers and in the sentence is equivalent.

✏️  Fix a couple of typos in tutorial

---

trio/tests/test_ssl.py

Build showed broken in a dependabot PR based on a newer version of 3.10.  https://github.com/python-trio/trio/pull/2042/checks?check_run_id=2881767897

update tests for SSL related deprecations in 3.10

---

trio/_core/_parking_lot.py

according to git -S the last occurance of next(_counter) was removed in 9cc347779ff520299f9b6639bc75e5cae2d898f7

remove unused global trio._core._parking_lot._counter

---

newsfragments/2063.bugfix.rst
trio/_core/_ki.py
trio/_core/_multierror.py
trio/_core/_run.py
trio/_core/tests/test_multierror.py
trio/_core/tests/test_run.py

from `MultiErrorCatcher.__exit__`, `_multierror.copy_tb`, `MultiError.filter`, `CancelScope.__exit__`, and `NurseryManager.__aexit__` methods.  This was nearly impossible to catch until #1864 landed so it wasn't cleaned up in #1805 (or during the live stream: https://www.youtube.com/watch?v=E_jvJVYXUAk).
@belm0: curious if this shows up in your application benchmarking.

test and eliminate additional sources of cyclic garbage

---

test-requirements.txt

black 21.8b0 forbids typing-extensions 3.10.0.1 on Python 3.10.

Fix Python 3.10 build

---

docs/source/reference-lowlevel.rst

Remove redundant f-string. Replace redundant loop variable with underscore.

docs: fix minor code example issues

---

newsfragments/2193.bugfix.rst
newsfragments/README.rst
trio/_subprocess.py
trio/_subprocess_platform/__init__.py
trio/_unix_pipes.py
trio/_windows_pipes.py
trio/tests/test_subprocess.py

If subprocess spawning fails (i.e. unsuccessful call to `exec`), the
created trio resources (i.e. the trio ends of the pipes that will be
used to send/receive data to the child) don't get cleaned up until the
next garbage collection run (which will call their `__del__`).
It would be nicer if this was deterministic, and that resources
created during the run of `open_process` were either completely
transferred to the `Process` object (which can take over the
management of them) or cleaned up (on failure).
To implement this, two ExitStacks are used: One will manage the
resources that need cleaned up unconditionally (the child ends of the
pipe); the other will manage the resources that need cleaned up on
failure.
Trio currently supports versions of python that lack …

Fix leaking file descriptors when subprocess creation fails

---

trio/tests/test_subprocess.py

On macOS, there appears to be some sort of race where sending SIGTERM
to a process "too early" in its lifetime causes the exit status to
appear as if SIGKILL was sent.
I can reproduce this with the stdlib subprocess. Additionally, this
problem doesn't occur if there is a tiny sleep between spawning a
child subprocess and terminating it.
My proposal is to use `/bin/sleep` on posix (which reliably does not
have this issue on macOS) and continue using the Python form elsewhere.
Related to #851. Originally submitted as #2190 (I was a bit too hasty in cleaning up my old branches)

Improve stability of tests_subprocess

---

test-requirements.in
test-requirements.txt

GitHub keeps annoying me about https://github.com/advisories/GHSA-pq7m-3gw7-gq5x so I figured I would cave in and update to 7.x (since 8.x does not support Python 3.7).
I also made sure to run pip-compile using Python 3.7, which restores a few dependencies that are probably not needed with later versions.

Bump ipython to 7.31.1

---

trio/tests/test_unix_pipes.py

On ppc64el, PIPE_BUF is 8192 but make_clogged_pipe() ends up writing a
total of 1048576 bytes before the pipe is full, and then a subsequent
receive_some(10000) isn't sufficient for orig_wait_writable() to return
for our subsequent aclose() call. It's necessary to empty the pipe
further before this happens. So we must loop until the pipe is empty to
make sure that the sender wakes up even in this case. Otherwise
patched_wait_writable() never gets to the aclose(), so
expect_closedresourceerror() never returns, the nursery never finishes
all tasks and this test hangs.

Fix test_close_at_bad_time_for_send_all on ppc64el

---

newsfragments/1104.feature.rst
newsfragments/1104.removal.rst

It turns out towncrier will ignore the removal and only consider the
feature, which means we have to merge them.

Merge two competing newsfragments

---

docs/source/awesome-trio-libraries.rst

* purerpc - not maintained, depends on ancient anyio version
* trio-jsonrpc - not maintained

unawesome unmaintained libraries

---

trio/_core/_multierror.py

This avoids:
============================= test session starts ==============================
platform linux -- Python 3.11.0a6, pytest-7.1.1, pluggy-1.0.0
rootdir: .../trio, configfile: pyproject.toml
collected 213 items
trio/_core/tests/test_asyncgen.py .
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File ".../trio/__venv__/lib64/python3.11/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File ".../trio/__venv__/lib64/python3.11/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …

Python 3.11: traceback_exception_init() has new keyword arguments

---

trio/tests/test_util.py

`asyncio.coroutine` has been removed in Python 3.11.

Fixed test failure on Python 3.11

---

trio/tests/test_ssl.py

We decided to merge #1921 knowing that we had this mysterious flaky test: https://gitter.im/python-trio/general?at=60c7cdc0184fef617ae9effc. We said we'd look into it later, and we should have, but we never did, and it fails at least 10% of the time, which is annoying.
cc @altendky @graingert @njsmith

Skip frequently failing test on Windows + 3.10

---

setup.py

https://spdx.org/licenses/
https://spdx.github.io/spdx-spec/SPDX-license-expressions/#d42-disjunctive-or-operator
As approved by @njsmith here: https://gitter.im/python-trio/general?at=6299a6fb4e38f759e29ffb3c

Make setuptools license field SPDX-compliant

---

trio/_sync.py
trio/tests/test_sync.py

Changes usages of `@async_cm` to using a mixin class for the same purpose.  No mechanical reason for it, but both pylance and pylint (possibly others, I didn't test past those and pycharm) complain about wrapped classes (ex: `trio.Lock`) not implementing `__aenter__` / `__aexit__`.  Really just a small change for my sanity.

replace `async_cm` decorator:

---

trio/_threads.py

Considering this queue exists just to block and receive one object and be destroyed, the more lightweight object should be preferred. It could have been used in the first place except that SimpleQueue was not implemented until python 3.7, and we have only recently dropped 3.6 support.

replace Queue with SimpleQueue in thread dispatch

---

trio/_threads.py
trio/tests/test_threads.py

The cancellable argument is typed bool but at runtime will work with any object with truthiness. However, if someone passes something like an numpy ndarray, with no notion of truthiness, the error is raised in an abort function and causes a TrioInternalError.
There are other unguarded uses of user arguments in abort functions, but they are in the lowlevel namespace, and aren't expected to have robust guardrails.

Guard rail cancellable argument of thread dispatch

---

trio/_subprocess.py

There is a small typo in trio/_subprocess.py.
Should read `subprocess` rather than `subproces`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, subproces -> subprocess

---

trio/tests/test_threads.py

removes a subtle early execution of a time.sleep call in the main thread. All the time and deadline stuff is not actually necessary in the happy path.

fix typo and extra sleep in test_unsafe_cancellable_kwarg

---

docs/source/reference-core.rst

Clarify docs on checkpoints in async iterables

---

docs/source/reference-lowlevel.rst

Reverts python-trio/trio#2414 per https://gitter.im/python-trio/general?at=631490ca11a6a83d049a8631
also, clarify the code with a comment and by minimizing the scope of acquire's "retry"

Revert "docs: fix bug in NotVeryGoodLock example"

---

docs/source/reference-core.rst

`handle_keyerror` and `handle_indexerror` should be represented with `(s)` e.g `handle_indexerrors`

Corrected Grammer

---

docs/source/conf.py

change the "python" link back to /3 when Python 3.11 is released

---

newsfragments/1810.feature.rst
trio/_socket.py
trio/tests/test_socket.py

Fixes #1810 (at least the second part, the first I can't reproduce).
Small and easy fix.

Add address in error message from trio.socket.socket upon connection failure

---

setup.py
test-requirements.in
trio/_core/_ki.py
trio/_core/tests/test_asyncgen.py
trio/_core/tests/test_ki.py
trio/_util.py
trio/testing/_sequencer.py
trio/tests/test_dtls.py
trio/tests/test_ssl.py
trio/tests/test_subprocess.py

Moved to the section of test dependencies in `test-requirenments.in` but all tests that require it are also guarded with skips. I didn't regenerate `test-requirements.txt` as that led to a couple changes irrelevant to this PR.
I considered giving a deprecation warning if it detects usage of `@async_generator`, but since aclosing() is only available on >=3.10 and trio supports >=3.7 there are still legitimate uses of it.
Thanks to @belm0 for giving the suggestion of handling checking for `@async_generator` that I ultimately went with.
Fixes #2458

remove async_generator as dependency

---

trio/_core/_ki.py
trio/_subprocess.py
trio/testing/_sequencer.py
trio/tests/test_windows_pipes.py

Came across a few type hints embedded in comments. I figured it was a good idea to update these.
I leverage postponed evaluation of annotations in a few places. This allows me to get away with fewer imports from `Typing`, since I can use a more modern annotation style. Look for:
```py
from __future__ import annotations
```

Update old style type hints

---

trio/tests/test_ssl.py

I was prompted by @pquentin to create a PR along these lines. See: https://github.com/python-trio/trio/pull/2480
We have certain SSL-related tests that are failing with Python 3.7 running on Ubuntu. Disabling them makes some sense, as Python 3.7 is reaching EOL in less than a year.
We continue to support Python 3.7, as the issue most likely is in the test suite.

Disable failing tests for Python 3.7 on Ubuntu

---

newsfragments/1148.feature.rst
trio/_core/_thread_cache.py
trio/_threads.py
trio/tests/test_threads.py

Fixes #1148
This doesn't work on windows, requiring an entirely separate mechanism (https://stackoverflow.com/a/16199587). It should be possible to get working on Mac (https://stackoverflow.com/a/7989973), but not having a mac machine I need the CI to test that for me. BSD variants also might need slightly different code, but I won't bother with that not having a way to test it. I haven't added a decorator on the test, so will probably see failed tests on other OS's for now.
The default in #1148 was suggested to be "Thread for {trio.lowlevel.current_task().name" by @njsmith - but pthread limits thread names to 15 characters so that's kind of a bad default. Wasn't sure what else to have though so that's the current default, but we probably want something else.
I currently set the thread …

Add name parameter to to_thread.run_sync [SQUASH]

---

setup.py
test-requirements.in

I've run MyPy and pytest against this locally with the new minimum attrs version installed to make sure this bump fixes the problem.
Would've waited until #2449 was merged to open this but that seems a bit stalled.
Fixes: #2439

Bump the minimum attrs ver for @frozen

---

trio/_unix_pipes.py

Complete type annotations for the `_unix_pipes` module.

Add types to `_unix_pipes`

---

trio/_unix_pipes.py

hi!
#2502 added a runtime dependency on `typing_extensions` but did not update the packaging config to specify this dependency.
presently no runtime features of `typing_extensions` are being used, so it does not need to be a dependency at runtime.
(I have not included a changelog entry here since #2502 did not either and the bug this fixes was never user-facing.)

Fix crash due to runtime import of `typing_extensions`

---

mypy.ini
trio/_core/_run.py

This PR adds some uncontroversial annotations to the central `trio.run` method. From my perspective, it is mainly intended as an experiment into whether a gradual, opportunistic approach to adding types to this project is feasible.

Add some low-effort type annotations

---

trio/_channel.py
trio/_core/__init__.py
trio/_core/_traps.py
trio/lowlevel.py

Fixes #1327
I didn't figure out a good way to add tests for it, but I reproduced the error from the original PR, and it now works as expected (in a somewhat pared down variant of it):
```python
from trio import open_memory_channel, MemorySendChannel, MemoryReceiveChannel
from typing import cast, Tuple
OutboundBroadcastChannelPair = Tuple[
MemorySendChannel[int],
MemoryReceiveChannel[int],
]
(outbound_send_channel, outbound_receive_channel) = cast(
OutboundBroadcastChannelPair, open_memory_channel(100)
)
outbound_send_channel.send_nowait(5)
outbound_send_channel.send_nowait(None) # argument 1 has incompatible type
reveal_type(outbound_receive_channel.receive_nowait()) # revealed type is builtins.int
```
One way would be to add type hints to the tests in `trio/tests/test_channel.py`, and …

Add generic typing support for Memory[Send/Receive]Channel

---

.github/workflows/ci.yml

We don't need every ubuntu job to have high permissions or checkout the head ref, only those issued by dependabot.
Unfortunately, we can't know if it fixes dependabot until merging!

split highly permissioned dependabot autoformatter into separate job

---

docs/source/code-of-conduct.rst
docs/source/contributing.rst
newsfragments/970.doc.rst
trio/_core/_run.py

Closes #970, rebased and refined from #972.
Also replaces two unrelated `’` 'smart' singlequotes with `'` ascii singlequotes, since there was one in the docstring I edited.

Document that new tasks from `nursery.start_soon()` may start in any order

---

.github/workflows/autodeps.yml

Currently it's failing because https://github.com/python-trio/trio/actions/runs/4853254871/jobs/8649206439#step:6:56
I think this fixes that? Not sure.

Ensure our autodeps workflow adds the new files

---

trio/tests/test_dtls.py

observation: any autojump threshold over 0 takes MUCH longer than 0
hypothesis: 10 second timeout cscope at the end of test is spuriously cancelling attempts on slow machines
experiment: set a minimal threshold and scale back # of handshakes to finish in a reasonable time, check if CI timeouts are avoided

use autojump_threshold in test_handshake_over_terrible_network

---

docs/source/awesome-trio-libraries.rst

docs: Fix library URL for flake8-trio

---

.github/workflows/ci.yml
ci.sh

Fixes https://github.com/python-trio/trio/issues/2650
I'm not sure this works. We'll see!

Replace codecov with their GHA thing

---

docs-requirements.in
trio/_socket.py
trio/_tests/test_socket.py

I see we have an extra dependency in `docs-requirements.in` (`async_generator`). But I'm not sure if I should include that in this. I'm leaning towards no.

Clear some cruft from 3.6

---

ci.sh
trio/_tests/test_exports.py

This makes *some* of the tests slower cause it stops using an (implicit) cache in CWD. This makes them generally faster, however.
Fixes https://github.com/python-trio/trio/issues/2662
Edit: huh, did not realize I pressed the "assignees" button!

Make the mypy-based tests faster!

---

trio/_core/_tests/test_run.py

Marks the remaining fail in #2646 as xfail so CI tests can fully "succeed" and status goes back to indicating whether tests passed or not.
Also removes a couple unused imports in the file

xfail test_nursery_cancel_doesnt_create_cyclic_garbage on 3.12

---

newsfragments/2493.breaking.rst
trio/_tests/test_timeouts.py
trio/_timeouts.py

Fixes #2493
Consolidated all `ValueError` tests into a single test.

timeout functions now raise ValueError on NaN inputs

---

.coveragerc
ci.sh
test-requirements.in
test-requirements.txt
trio/_core/_tests/test_multierror.py
trio/_core/_tests/test_multierror_scripts/_common.py
trio/_core/_tests/test_multierror_scripts/apport_excepthook.py

Not sure this will work. Fixes https://github.com/python-trio/trio/issues/2645

Try out coverage instead of pytest-cov

---

setup.py

Currently https://pypi.org/project/trio/ renders weirdly. I haven't tested this actually fixes it but I do believe it does.

Render long description as ReST

---

test-requirements.in
test-requirements.txt
trio/_tests/test_exports.py

This is making our static tool tests fail.

Prevent typing_extensions 4.7.0

---

docs/source/history.rst
newsfragments/1148.feature.rst
newsfragments/1810.feature.rst
newsfragments/2333.bugfix.rst
newsfragments/2462.bugfix.rst
newsfragments/2493.breaking.rst
newsfragments/970.doc.rst
trio/_version.py
trio/tests.py

- Fixes https://github.com/python-trio/trio/issues/2655
- Fixes https://github.com/python-trio/trio/issues/2485 (and duplicate https://github.com/python-trio/trio/issues/2583)

Release 0.22.1

---

docs/source/reference-core.rst

Normally I wouldn't make such a trivial PR, but this is such an excellent quote that I think it deserves to be fixed.

Fix typo in reference-core.rst

---

docs/source/reference-core.rst
docs/source/tutorial.rst

Issue: Documentation doesn't aligns with the code block's line number.
In image format:

Docs: Fix line numbers on tutorial.rst

---

docs-requirements.txt

Partially reverts python-trio/trio#2715, which was merged with failing tests as it wiped out a bunch of lines from `docs-requirements.txt`

Partially revert "Bump certifi from 2023.5.7 to 2023.7.22"

---

pyproject.toml
trio/_highlevel_open_tcp_stream.py
trio/_tests/verify_types.json
trio/socket.py

This PR adds type annotations to `_highlevel_open_tcp_stream.py`
I would love feedback and any comments on how this could be improved to be more accurate.

Typing highlevel open tcp stream

---

pyproject.toml
trio/_tools/gen_exports.py

This PR adds type annotations to `_tools/gen_exports.py`
I would love feedback and any comments on how this could be improved to be more accurate.

Add typing to `_tools/gen_exports.py`

---

trio/_core/_mock_clock.py
trio/_tests/verify_types.json

This PR adds missing type annotations to `_core/_mock_clock.py`.

Add missing type annotations to `_core/_mock_clock.py`

---

docs/source/conf.py
pyproject.toml
trio/_core/_thread_cache.py
trio/_tests/verify_types.json

Add types to `core._thread_cache`

---

check.sh
pyproject.toml
trio/_core/_generated_run.py
trio/_core/_io_common.py
trio/_core/_ki.py
trio/_core/_parking_lot.py
trio/_core/_tests/test_io.py
trio/_core/_tests/test_ki.py
trio/_core/_tests/test_multierror.py
trio/_core/_tests/test_multierror_scripts/apport_excepthook.py
trio/_core/_tests/test_multierror_scripts/ipython_custom_exc.py
trio/_core/_tests/test_multierror_scripts/simple_excepthook.py
trio/_core/_tests/test_run.py
trio/_core/_wakeup_socketpair.py
trio/_path.py
trio/_tests/check_type_completeness.py
trio/_tests/test_contextvars.py
trio/_tests/test_dtls.py
trio/_tests/test_exports.py
trio/_tests/test_fakenet.py
trio/_tests/test_highlevel_serve_listeners.py
trio/_tests/test_socket.py
trio/_tests/test_subprocess.py
trio/_tests/test_threads.py
trio/_tests/test_tracing.py
trio/_tests/test_unix_pipes.py
trio/_tools/gen_exports.py
trio/_unix_pipes.py
trio/testing/_fake_net.py

This is a squash of #2721 to avoid having to navigate a huge and messy PR. It consists of a ton of small fixes or `type: ignores` to any file that raised errors when running `mypy trio/`, and it also transitions `pyproject.toml` from being a list of files to check strictly, to an ignore-list with files to disable strict checks for. This doubles as a TODO-list, and it's easy to explode wildcards, or remove a disabled check, or similar.
The test changes has caught several small typing errors introduced in various PRs that haven't been checked in CI, or when files have been forgotten to get added.
All the changes should be non-controversial, if anything is up for debate I'll just mark it with a comment and/or revert it, and add it to #2734 or directly split out to a separate PR

Fix various files so the entire trio/ directory can be type-checked

---

pyproject.toml
trio/_core/_tests/test_multierror.py
trio/_socket.py

This PR enables mypy's local partial types option, because as mypy says,
> This is always implicitly enabled when using the [mypy daemon](https://mypy.readthedocs.io/en/stable/mypy_daemon.html#mypy-daemon).
leading to differences in reported errors if people like myself use the mypy daemon as a code editor extension.
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-local-partial-types

Enable local partial types

---

docs/source/contributing.rst

Follow up to #2744, this PR updates the documentation to talk about using pre-commit for code formatting instead of only talking about using black.

Update `contributing.rst` to talk about pre-commit

---

trio/_tests/check_type_completeness.py
trio/_tests/verify_types_darwin.json
trio/_tests/verify_types_linux.json
trio/_tests/verify_types_windows.json

cc @jakkdl hopefully this still accomplishes the goals you wanted when you originally made all the diagnostics happen.

Fix pyright output

---

pyproject.toml
trio/_tests/check_type_completeness.py

This fixes the issues that were causing mypy to fail, extracted from #2773.

Fix typecheck failures in `master`

---

MANIFEST.in

#2775
`py.typed` was not included in distributions, so add it in `MANIFEST.in`.

Add py.typed in MANIFEST.in

---

trio/_core/_run.py
trio/_core/_tests/test_run.py
trio/_threads.py

This PR aims to fix the type errors introduced in #2696 and #2700, while leaving the multierror fixes for #2787.

Fix type errors introduced when #2696 and #2700 were merged

---

trio/_core/_multierror.py

At the moment, this is only ignoring generics not matching properly in the subclass. If anyone has any better ideas on how to handle this, feel free to try it out.

Attempt to fix multierror typing

---

.github/workflows/ci.yml

Recently the static checks do more than just black and isort. Recent errors like #2783 and #2777 would be caught this way, and it would make it less error prone to rebase some old PRs that lack typing.
Notably this PR won't pass until #2783 and maybe others are fixed. Whenever master shows green on status checks, someone needs to tickle the update and merge buttons.

Require static checks to pass in CI

---

.coveragerc

As suggested by @Zac-HD in https://github.com/python-trio/trio/pull/2702#issuecomment-1705865851
Maybe not as necessary with #2772 and I personally view coverage diffs on `app.coverage.io`, but I don't see any reason not to enable this.

enable skip_covered in coveragerc

---

trio/_core/_ki.py
trio/_tests/verify_types_darwin.json
trio/_tests/verify_types_linux.json
trio/_tests/verify_types_windows.json

This should fix the `trio.Lock` issue in https://github.com/python-trio/trio/issues/2775.

Fix KI protection decorator

---

pyproject.toml
trio/_signals.py
trio/_tests/test_signals.py

This is fairly straightforward, but I did extract a test helper method into a function. This allows `open_signal_receiver()` to be typed as producing an `AsyncIterator`, keeping `SignalReceiver` internal.

Add types to `_signals`, `test_signals`

---

trio/_subprocess.py

EDIT: assumptions were wrong
Ended up researching this during discussion in #2792, and thought I might as well add a comment (and an assertion to double-check assumptions). Also cleared up a coverage miss for an error that shouldn't trigger in test runs.
One could possibly raise a warning instead of the assertion to be *extra* defensive, but afaict it *really* shouldn't trigger on 3.9+ so the assertion+message is already very defensive IMO.
https://docs.python.org/3/library/os.html#os.pidfd_open

Add comment and assertion to `pidfd_open` workaround

---

docs/source/reference-io.rst

Fixes typo from "can can" to "can" in reference-io.rst

Fix typo in reference-io.rst

---

trio/_core/_run.py

Just some random lines I noticed in codecov that should pretty clearly be excluded.

get _core/_run to 100% coverage

---

newsfragments/543.headline.rst
setup.py

I think we can say the type hints for the library are complete, even if they are not entirely correct.
(Also I resorted the list to be alphabetical again...)
... Also I added a changelog entry.

Add typing classifier to trio + add typing changelog

---

pyproject.toml
trio/_tests/test_windows_pipes.py
trio/_windows_pipes.py

This PR adds type annotations for `_windows_pipes.py` and `_tests/test_windows_pipes.py`.

Add type annotations for windows_pipes and its test

---

notes-to-self/loopy.py
pyproject.toml
trio/_core/_tests/test_run.py
trio/_core/_tests/test_windows.py
trio/_tests/test_threads.py
trio/_tests/type_tests/check_wraps.py

This PR enables the flake8-async rule and fixes all the existing issues that were raised.

Enable flake8-async rule

---

trio/_tests/test_threads.py
trio/_threads.py

Should fix the timeouts @jakkdl worked on in #2827, which were introduced in #2392.  Some discussion from chat:
> @richardsheridan: the examples used seem to be extremely simple use cases where  we do `to_thread_run_sync(from_thread_run_X(afn))` back to back. if we can make a test that just loops for a few seconds doing that maybe it could reliably trigger the race for debugging? I won't be able to get to it for a while but just thinking out loud in case someone else wants to try first.
> @oremanj: richardsheridan: I just took another look at the threading code changes and I think there is a race here that I missed. When a host-task `run` completes, the host task immediately writes the result to the queue, which unblocks the thread and makes it possible for it to terminate. The thread's …

Fix thread reentry deadlocks

---

trio/_core/_tests/test_run.py

At least if I'm reading pytest output correctly.
Fixes #2646 and presumably https://github.com/python/cpython/issues/100964 can be closed as well.

nursery_cancel doesn't seem to create cyclic garbage on 3.12 anymore

---

.pre-commit-config.yaml

This PR enables the `sort-simple-yaml` pre-commit hook, and has it sort the `.pre-commit-config.yaml` file.
The intention is to give it order if changes ever happen in the future, but in the end it's personal preference.

Sort pre-commit config file

---

pyproject.toml
trio/_channel.py
trio/_core/_multierror.py
trio/_core/_parking_lot.py
trio/_dtls.py
trio/_highlevel_open_tcp_listeners.py
trio/_highlevel_ssl_helpers.py
trio/_subprocess.py
trio/_sync.py
trio/_tests/test_socket.py
trio/_threads.py

"But wait CoolCat, why do we need pyi if we aren't shipping stubs?"
Because some of the rule checks it does look like they might help notice bugs in PRs in process.
Full rule list section: https://docs.astral.sh/ruff/rules/#flake8-pyi-pyi

Enable flake8-pyi

---

trio/_core/_multierror.py

fixes #2464 
A slighly more general fix would be `if "apport_excepthook" in getattr(sys.excepthook, "__name__", "")` in case they make another slight change to the name of the function.
The issue mentioned that this broke as they updated to Ubuntu 22.10, and all the ubuntu builds in our CI runs on 22.04, which I assume is why this wasn't picked up by the test suite.
It would be great if @Adrien-Luxey or somebody else with easy access to an ubuntu 22.10 machine could run the test suite on master and then this PR to see if it is fixed.
Checking https://github.com/actions/runner-images#available-images it looks like 22.04 is the only available image, so would require a bunch of extra work to get this tested in CI.

extend apport excepthook detection to also detect partial_apport_excepthook

---

newsfragments/2842.removal.rst
trio/_highlevel_open_tcp_listeners.py
trio/_highlevel_ssl_helpers.py
trio/_tests/test_highlevel_open_tcp_listeners.py

This PR makes due on my comment in 6f9ab95349044dbb9d63408d2245dc95ad167f7e, removing support for `math.inf` as an argument for the tcp listener backlog, leaving only `int | None` as valid options.

Remove infinity support for tcp listener backlogs

---

trio/_threads.py

This was probably a bad merge during code review that slipped through

Remove redundant line from docstring of `to_thread_run`

---

newsfragments/2611.bugfix.rst
trio/_core/_run.py
trio/_core/_tests/test_run.py

proposed alternative fix and tests for #2611. fixes #2844.
note that these tests are parametrized:
> For the tests, there are currently enough separate cases that I can imagine missing that something is backwards. Could we write something parameterized, such that it obviously does each possible set of operations, and then the asserts only depend on whether we're in strict mode? (I expect this to be harder to read individually, but the confidence in consistency is what I'm after) --- https://github.com/python-trio/trio/pull/2826#issuecomment-1776252294

Fix regressions introduced when hiding `Nursery.start` implementation-detail nursery

---

newsfragments/2842.deprecated.rst
newsfragments/2842.removal.rst
pyproject.toml

Fixes https://github.com/python-trio/trio/issues/2846
cc @CoolCat467 about changing the category for your newsfragment.

Add removals as a newsfragment type

---

docs/source/history.rst
newsfragments/1457.feature.rst
newsfragments/2392.feature.rst
newsfragments/2611.bugfix.rst
newsfragments/2668.removal.rst
newsfragments/2696.feature.rst
newsfragments/2700.misc.rst
newsfragments/2702.removal.rst
newsfragments/2807.misc.rst
newsfragments/2841.deprecated.rst
newsfragments/2842.deprecated.rst
newsfragments/543.headline.rst
trio/__init__.py
trio/_version.py

Bump version to 0.23.0

---

src/trio/_tests/test_subprocess.py

While most OSes will have the `sleep` binary in `/bin`, this is not guaranteed (e.g. `/bin` only contains `sh` on NixOS). While in principle one might have an incompatible `sleep` somewhere in PATH, this seems unlikely.

Don't use absolute path for sleep binary in tests

---

src/trio/_tests/test_subprocess.py

Refs https://github.com/python-trio/trio/issues/2885
I've run the PyPy test suite a lot and this test in particular has failed.
See https://github.com/A5rocks/trio/actions/runs/6953123771/job/18951033826#step:5:5284 for an example of this happening.
I'm guessing that this is because PyPy GC is weird and isn't guaranteed to clean up previous test objects which might contain something with a file descriptor. I added this here and I didn't get this test to fail again in a bunch of runs, so I think this fixes that.
Now I'm kinda thinking of if it's possible to upstream this in pytest, because this kind of thing is insidious. https://foss.heptapod.net/pypy/pypy/-/commit/5a6a733370542b26e7c4ee756c4fb566523e53d8 introduces a new PyPy GC API that can address this more generally, I believe.

Address PyPy flakiness in test_for_leaking_fds

---

src/trio/__init__.py
src/trio/_tests/test_exports.py
src/trio/socket.py

Was looking at export tests for https://github.com/python-trio/trio/issues/2885 and spotted a few changes to make!
Refs https://github.com/python-trio/trio/issues/2885

Export test fixes

---

.pre-commit-config.yaml

When I am working on PRs, I tend to run `pre-commit run -a` a lot to make sure all files are checked, and I've noticed that black runs considerably slower than all the other checks. This PR changes the black hook used to [the official pre-commit mirror](https://github.com/psf/black-pre-commit-mirror) that uses a mypyc compiled version of black that is significantly faster.
Funny quote from black-pre-commit-mirror:
> mypyc wheels go brr

Switch to mypyc-compiled black mirror pre-commit hook

---

check.sh
docs-requirements.in
docs-requirements.txt
docs/source/conf.py
docs/source/local_customization.py
docs/source/typevars.py
pyproject.toml
test-requirements.in
test-requirements.txt

I was struggling with sphinx in #2898 and noticed that sphinx was pinned to an ancient version, and unpinning & updating it seemed to fix a couple of them. My struggles also made me understand sphinx innards better than I had before, so could fix a bunch of references at the same time.
* add missing type annotations to docs/source/*.py
* specify files to check with mypy in pyproject.toml (docs/source/typevars.py was typed already, but not checked in CI)
* change sphinx version limits to >5.3
* clean up & fix a bunch of references in sphinx
* add comment explaining workarounds
let's see if RTD manages this as well

Sphinx cleanups, bump version requirements, typecheck docs source files

---

src/trio/_core/_run.py

This pull request partially completes changes that were noted in #2908.
Either added on to this pull request or in another pull request, we still need to make sure to test that cython will continue working and not find these sorts of issues after they are already a problem.
Excerpt from original comment in #2908:
>But it would be good to also run a test for this in CI. We do have a test for the interpreter's built-in C coroutines (`test_async_function_implemented_in_C`) and I [njsmith] originally assumed that would be enough, but obviously it wasn't, so I guess we need to do the legwork to install cython in CI and build a tiny Cython module.

Cython Workaround

---

src/trio/_tests/test_fakenet.py
src/trio/_tests/test_highlevel_open_tcp_listeners.py

Error messages are slightly different when using musl libc.
The new regexes fix that.

fix test regexes for musl libc

---

pyproject.toml

This pull request enables ruff's `flake8-comprehensions` rule, building off of the formatting changes done in #2930.

Enable `flake8-comprehensions`

---

pyproject.toml
src/trio/_subprocess_platform/__init__.py
src/trio/_tests/test_file_io.py
src/trio/socket.py

This pull request enables ruff's `flake8-future-annotations` rule, building off of the formatting changes done in https://github.com/python-trio/trio/pull/2930.

Enable `flake8-future-annotations`

---

src/trio/_tests/type_tests/check_wraps.py
src/trio/_util.py
src/trio/lowlevel.py
src/trio/socket.py

Noticed this when reviewing #2932. For context, `from typing import` is what's used everywhere else, with 110 matches in the repository when `grep`ing.
also one instance of `import typing_extensions`, where statistics are similar.

change all instances of 'import typing as ...' to 'from typing import ...'

---

newsfragments/2939.bugfix.rst
src/trio/_core/_thread_cache.py
src/trio/_tests/test_threads.py

Fix the `pthread_getname_np` and `pthread_setname_np` search logic to support vanilla versions of musl and CPython, e.g. as used on Gentoo musl systems.  On such systems, there is no "libpthread.so" (there is only a static library) and the relevant functions are found in "libc.so".  Additionally, `ctypes.util.find_library("c")` does not work because of an old unsolved bug in CPython (linked in the code).
To resolve the problem, add a fallback to trying `libc.so` if no pthread library can be found.  This roughly covers three possibilities:
- a "typical" system with `libpthread.so` will find that library and use it
- a musl system will fall back to `libc.so`, load that library and find pthread functions there
- any other system will try to load `libc.so`, and fail
The code in …

Fix finding pthread_*name_np on vanilla musl libc

---

.github/workflows/ci.yml
src/trio/_tests/test_socket.py
src/trio/_tests/test_threads.py

Ref: https://github.com/python-trio/trio/issues/2885

Add Alpine to CI

---

src/trio/_core/_run.py
src/trio/_core/_tests/test_run.py

In preparation for eventual deprecation of `strict_exception_groups=False` (https://github.com/jakkdl/trio/tree/deprecate_exceptiongroups_false) we probably shouldn't rely on it ourselves in the internal code.
#2611 - the original issue where errors raised before `task_status.started()` got double-wrapped
#1599 - for why the old nursery *can* have multiple tasks.
#2844 - the regression error that occured after my initial fix for #2611 in #2826
Fairly straightforward implementation, other than perhaps exactly what to raise when multiple exceptions do occur. The main code that tests this is `test_trio_run_strict_before_started`, I added the new test after it only to trigger the case where multiple exceptions do pop up in the old nursery.

Replace usage of strict_exception_groups=False in Nursery.start

---

src/trio/_core/_run.py
src/trio/_core/_tests/test_run.py
src/trio/_tests/test_deprecate_strict_exception_groups_false.py
src/trio/_tests/test_subprocess.py

Wasn't totally sure which issue to refer to, ended up going with #2929
the removed `with` block in `test_subprocess` was added to try and track down some weirdness in https://github.com/python-trio/trio/pull/2886#discussion_r1449035885 - but I don't think it served much of a purpose in the end, so opted now to remove it instead of wrapping it in a `pytest.warns`.

add deprecation warning for specifying strict_exception_groups=False

---

.github/workflows/autodeps.yml
.github/workflows/ci.yml

This pull request switches the workflow system to use checkout v4 and setup-python v5.
EDIT:
`checkout` change does updating node runtime:
https://github.com/actions/checkout/releases/tag/v4.0.0
`setup-python` change does updating node runtime and dependencies:
https://github.com/actions/setup-python/releases/tag/v5.0.0

Switch to `actions/checkout@v4` and `actions/setup-python@v5`

---

docs/source/awesome-trio-libraries.rst

I think my little aioresult library ([github](https://github.com/arthur-tacca/aioresult), [docs](https://aioresult.readthedocs.io/en/v1.0/overview.html), [PyPI](https://pypi.org/project/aioresult/)) could be useful to some, so this would add it to the list of Awesome Trio Libraries in the Trio docs.

Add aioresult to Awesome Trio Libraries in the docs

---

.github/workflows/ci.yml

Reference: https://github.com/python-trio/trio/issues/2885
This was mentioned elsewhere recently cause they're kinda flakey (nightly means that pypy problems become our problems)

Remove PyPy nightly runs

---

docs/source/reference-testing.rst
newsfragments/2937.feature.rst
src/trio/_tests/test_threads.py
src/trio/_threads.py
src/trio/testing/__init__.py

Add trio.testing.wait_all_threads_completed

---

docs/source/awesome-trio-libraries.rst

I've just released [`logot`](https://github.com/etianen/logot), a testing library with some nice tools for testing highly-concurrent async code using log capture. It includes a [`trio` integration](https://logot.readthedocs.io/latest/integrations/trio.html), so it would be great to add it to the list of testing tools in your docs. ❤️ 
Here's a quick example of how the `trio` integration looks:
``` py
from logot import Logot, logged
async def test_app(logot: Logot) -> None:
async with trio.open_nursery() as nursery:
nursery.start_soon(app.start())
await logot.await_for(logged.info("App started"))
```
Of course I'd welcome any feedback you have on the `trio` integration too! 🙇

Added link to `logot` in docs

---

src/trio/_abc.py
src/trio/_tests/test_highlevel_open_tcp_listeners.py
src/trio/_tests/test_highlevel_open_tcp_stream.py
src/trio/_tests/test_highlevel_ssl_helpers.py
src/trio/testing/_fake_net.py

`_socket.getaddrinfo` takes care of encoding all passed in `str` host arguments before passing it to a custom resolver. Additionally, the docs say that a resolver will always receive IDNA-encoded bytes.
However, the type hints of `HostnameResolver.getaddrinfo` imply that a resolver may need to contend with a `str`
Remove the extraneous appearance

Remove incorrect `str` possibility from HostnameResolver.getaddrinfo

---

docs/source/contributing.rst

Updated Google Docstring Format link since currently it points to a 404 page.
Fixes https://github.com/python-trio/trio/issues/2546

fix: updated the google docstring url

---

.github/workflows/autodeps.yml

This pull request adds `pre-commit run --jobs 0` to the autodeps run.
I didn't see this listed in the documentation anywhere, [but marking `0` for number of jobs uses maximum number of threads](https://github.com/pre-commit/pre-commit/blob/ddbee32ad0722a0bc216bc29ee29a1885454bd78/pre_commit/commands/autoupdate.py#L178).

Add pre-commit autoupdate to autodeps

---

docs/source/awesome-trio-libraries.rst
pyproject.toml
src/trio/_core/_run.py

This registration was previously handled by pytest-trio (before Hypothesis supported entry-point plugins).  Upstreaming it means that we'll get the behavior we want for unittest, for functions people call by hand, and so on.  Fixes https://github.com/python-trio/trio/issues/2981.  Manual testing with Hypothesis confirms this works, and our existing determinism-related unit tests continue to pass, so I haven't added more complicated tests which would require subprocesses and installing Hypothesis.
I'll open a PR to remove the relevant logic from pytest-trio once this has been released; double-registration is perfectly safe so it's better to overlap than leave a gap.
Plus some bonus updates to the awesome-trio-libraries page, since I noticed outdated information there.

Ensure we're deterministic for Hypothesis in Trio, not pytest-trio

---

.pre-commit-config.yaml
newsfragments/2987.issue.rst
src/trio/_path.py
src/trio/_tests/test_path.py

I am developing an application that runs on the Windows embedded Python package. It appears that the embedded Python standard library does not include docstrings which means an unhandled exception is raised when importing trio because of a couple `assert X.__doc__ is not None` statements. This PR makes it so `__doc__` is allowed to be `None`.
To test, I am using [Python Windows Embedded 64-bit 3.11.8](https://www.python.org/downloads/release/python-3118/) package. I wrote a small script to show that `__doc__ is None` on every Path function:
```python
import inspect
from pathlib import Path
for name in dir(Path):
if name.startswith("_"):
continue
attr = getattr(Path, name)
if inspect.isfunction(attr) or inspect.ismethod(attr):
if attr.__doc__ is None:
print(f"Path.{name}.__doc__ is None") …
```

Path decorators: allow empty docstrings to support embedded Python

---

docs/source/conf.py
docs/source/reference-core.rst
src/trio/_core/_run.py
src/trio/_subprocess.py

Closes https://github.com/python-trio/trio/issues/2929, by ensuring that our docs present `strict_exception_groups=True` as the natural default (and it is indeed the default in current Trio, as well as the _only_ behavior of asyncio and anyio).
Following discussion on that issue, I've also written up some notes on three ways of handling `ExceptionGroup`s before raising to user code: (1) defer-to, (2) single-error, optionally handling background and foreground tasks differently, and (3) simply letting it propagate to the caller.
2b might actually be a neat option to add to `trio.open_nusery()` itself, but I'd want to see a proof-of-concept judged useful downstream before we committed to supporting it there.

Document strict ExceptionGroups as the natural default

---

src/trio/_tests/tools/test_gen_exports.py

https://github.com/python-trio/trio/pull/2988 was closed, but I think we agree that `test_run_black` can be removed. I don't actually remember why it was introduced, but using blame all the way back leads to it not seeming necessary. It was made because `test_lint_failure` wouldn't check that `ruff` was actually running, so we duplicated that to have a `black`-specific test and a `ruff`-specific test. The `ruff` one is still useful (maybe), but the `black` one is duplicated.
I'm not so sure *any* of these tests should exist anymore. I think I kinda pushed for the `ruff`-specific one but now I think it's ultimately unnecessary. If `ruff` doesn't run in `gen_exports`, that's ... fine. We have CI jobs dedicated to checking our code is alright and if it isn't, then that will be caught. …

Remove `test_run_black`

---

docs/source/history.rst
newsfragments/2987.issue.rst
src/trio/_version.py

Note: I renamed `2987.issue.rst` to `2987.bugfix.rst`.
I wanted to make this release a while ago but so it goes. This is mainly for `strict_exceptiongroups` reasons (we now have documentation!).

Bump version to 0.25.1

---

src/trio/_threads.py

Added a documentation fix for the following issue: fixes https://github.com/python-trio/trio/issues/1439.

Updated docstring for from_thread_run to reflect how to get trio token

---

docs/source/awesome-trio-libraries.rst

Just a minor update in the awesome-trio-libraries list

update docs: flake8-trio has been renamed to flake8-async

---

src/trio/_repl.py
src/trio/_tests/test_repl.py

A follow up to #2972. These would have been review comments earlier if I knew the code was going to be (a) this simple and (b) in my wheelhouse!
I think `runcode` can just be:
``` python
def runcode(self, code: types.CodeType) -> None:
try:
func = types.FunctionType(code, self.locals)
if inspect.iscoroutinefunction(func):
trio.from_thread.run(func)
else:
trio.from_thread.run_sync(func)
except SystemExit:
raise
except BaseException:
self.showtraceback()
```
It's less code, less layers of onion unwrapping, and the more common `from_thread.run_sync` is more efficient (not that anyone would notice latency from two extra checkpoints at the REPL). That's the first commit.
I also noticed one fragility, which is that KI works thanks to the thread task reentry feature combined with the fact that …

tweaks to new REPL

---

src/trio/_abc.py

[Since 3.7](https://github.com/python/cpython/issues/74648), CPython provides slots for `abc.ABC`. I'm not sure about pypy but a) they use the same stdlib so probably and b) slots on pypy don't mean anything.
This means trio can use `abc.ABC` instead of `abc.ABCMeta`.

Use `abc.ABC` rather than `abc.ABCMeta`

---

docs/source/reference-core.rst
src/trio/_core/_run.py

Documents the changes made in https://github.com/python-trio/trio/pull/1696 more explicitly.

[docs] clarify checkpoint semantics for trio.open_nursery

---

docs/source/conf.py
src/trio/_core/_run.py
src/trio/_tests/type_tests/raisesgroup.py
src/trio/_tests/type_tests/task_status.py
src/trio/_util.py
src/trio/testing/_raises_group.py

This causes annotations to default to `TaskStatus[None]`, `RaisesGroup[BaseException]` and `Matcher[BaseException]`, instead of `Any`. [`_socket`](https://github.com/python-trio/trio/blob/451393acec35c3a01cba0c19de6bf8f6f23dbc7b/src/trio/_socket.py#L41-L52) could also use this to make `SocketType` generic over `AddressFormat`, but I'm not really sure how that should behave.

Use Typevar defaults for `TaskStatus` and `Matcher`

---

README.rst
docs/source/contributing.rst
docs/source/index.rst
docs/source/releasing.rst

This is just finishing what I already started.
Note: the old links still work so there isn't any rush on merging this.

Update old references to `master` branch to be `main`

---

src/trio/_tests/test_trio.py
src/trio/_tests/tools/test_mypy_annotate.py
src/trio/_threads.py

https://github.com/python-trio/trio/pull/3054 didn't catch everything. However the root cause was that pytest imports trio during plugin phase and doesn't handle deprecation warnings by erroring then.
To fix that, we can just clear the module cache and try importing again. I'm not completely sold on this idea but it's the best one I had and it works.

Fix attrs redone

---

docs/source/history.rst
src/trio/_version.py

Fixes https://github.com/python-trio/trio/issues/3053 for real this time.

Bump version to 0.26.2

---

docs/source/awesome-trio-libraries.rst

It seems like the projects were moved from gitlab to github.

Update quart-trio and hypercorn links

---

pyproject.toml
src/trio/_util.py

In this pull request, we enable ruff's `flake8-executable` and `flynt` rules. Only `flynt` suggested making any actual changes, as none of Trio's files have a shebang line.

Enable ruff's `flake8-executable` and `flynt` rules

---

pyproject.toml
src/trio/_core/_tests/type_tests/nursery_start.py

In this pull request, we enable ruff's `refurb`, `flake8-import-conventions`, `flake8-pie`, and `flake8-quotes` rules, all of which make very minor changes if any.

Enable more minor ruff rules

---

.github/workflows/check-newsfragment.yml

Fixes https://github.com/python-trio/trio/issues/3048
This is something way too easy to forget: hence, automation. I don't think the screening done here is great, but hopefully it's good enough for now?

Check for newsfragments

---

.pre-commit-config.yaml
src/trio/_tests/tools/test_gen_exports.py
src/trio/_tools/gen_exports.py

Making true on https://github.com/python-trio/trio/issues/2835#issuecomment-2266175000, in this pull request I add a local pre-commit hook that automatically regenerates all the generated files if either the generated file itself or the files used to create them are edited. The only one it doesn't match at the moment is `gen_exports.py` itself, and I could add this if needed.

Regenerate generated files automatically if any are changed

---

.github/workflows/autodeps.yml

This avoids having to manually update the lockfile and allows for easier regression testing (rather than having to trawl through a failing check.sh run).

Update `uv`'s output when it gets bumped in autodeps

---

.github/workflows/ci.yml

Latest PyPy release stopped supporting Python 3.9.

Stop testing PyPy's Python 3.9

---

src/trio/_tests/test_exports.py
test-requirements.in
test-requirements.txt

Refs https://github.com/python-trio/trio/issues/2885
I remember jedi being somewhat flaky on PyPy so this should fix that.

Enable mypy and disable jedi on PyPy

---

.pre-commit-config.yaml

Mentioned in and closes https://github.com/python-trio/trio/issues/3082, this pull request adds the sphinx-lint pre-commit hook

Add sphinx-lint

---

.github/workflows/ci.yml
newsfragments/3076.bugfix.rst
src/trio/_subprocess.py
src/trio/_tools/gen_exports.py

This should resolve the issue mentioned in Gitter

Update open process types

---

newsfragments/3095.bugfix.rst
src/trio/_tests/test_timeouts.py
src/trio/_timeouts.py

trio.sleep_forever should be NoReturn

---

docs-requirements.in
docs-requirements.txt
docs/source/conf.py

Fixes #3064
I'm not sure whether this is required because the docs look fine, but then of course the docs have very many hacks that I'm not aware of.

Handle RTD enabling addons

---

newsfragments/3113.doc.rst
src/trio/_timeouts.py

Document that `trio.sleep_forever` will raise `RuntimeError` instead of returning

---

.pre-commit-config.yaml

In this pull request, we allow pre-commit.ci to autofix pull requests. The specific pre-commit hooks we use are all designed well and will avoid making changes that might cause issues, and people usually end up saying the trigger message to fix their pull requests anyways.

Enable pre-commit.ci pull-request autofixing

---

src/trio/_core/_tests/test_guest_mode.py
src/trio/_core/_tests/test_ki.py
src/trio/_signals.py
src/trio/_tests/test_repl.py
src/trio/_tests/test_signals.py
src/trio/_tests/test_util.py
src/trio/_util.py

I noticed `signal.raise_signal` seems to do what `signal_raise` used to. Let's use that instead.

Get rid of `signal_raise`

---

src/trio/_tests/test_socket.py

`test_socket.py:test_sniff_sockopts` creates an IPv6 socket even if IPv6 is disabled. This PR changes the test to only create the socket if IPv6 is available.

Don't create IPv6 socket if IPv6 is disabled

---

.github/workflows/ci.yml

Fixes https://github.com/python-trio/trio/issues/3129
This is because "x86" pypy is just setup-python installing x64 pypy.

Only run x64 pypy

---

.pre-commit-config.yaml
pyproject.toml
src/trio/_dtls.py
src/trio/_socket.py
src/trio/_subprocess_platform/__init__.py
src/trio/_tests/test_testing_raisesgroup.py
src/trio/_tests/test_threads.py
src/trio/testing/_raises_group.py
test-requirements.in
test-requirements.txt

Hi! I just released Ruff 0.8.0. This release removes a few rules that had been deprecated for a few releases, so Ruff 0.8.0 would have started emitting warnings when linting trio due to the fact that you have some of these now-removed rules explicitly ignored in your Ruff config.
This PR gets rid of the removed rules from your Ruff config. There's also some additional changes made here; let me know if any of them are undesirable, and I can revert them:
- Some changes due to the recoding of the `flake8-type-checking` rules from `TCH` to `TC`
- Some changes due to the addition of the preview rule [`unraw-re-pattern`](https://docs.astral.sh/ruff/rules/unraw-re-pattern/)
- Some changes due to the addition of the preview rule [`redundant-none-literal`](https://docs.astral.sh/ruff/rules/redundan …

Bump Ruff to 0.8.0

---

newsfragments/3087.doc.rst
src/trio/_core/_run.py

Fixes #3087
Unfortunately I am unable to check this because I only have Linux and Windows available. This only happens on MacOS.

Improve error message for eventlet/gevent monkey patching

---

docs/source/conf.py
newsfragments/3141.bugfix.rst
src/trio/_tests/test_testing_raisesgroup.py
src/trio/_tests/type_tests/path.py
src/trio/_tests/type_tests/raisesgroup.py
src/trio/testing/_raises_group.py

@jakkdl because you wrote this / these comments
This should fix the typing weirdness around it. I didn't really look too hard at things originally so there might be some outdated comments.
Maybe also @TeamSpen210 because types
... also this might be easier to review commit by commit. I tried my best to keep things separated (eg staging hunks so that only related pieces were in a single commit). However, I did not run mypy / tests after every single commit so things may be broken after a commit.

Type `RaisesGroup` properly

---

.github/workflows/ci.yml

Step one of having a merge queue for trio, I think. Couldn't find any good references to check against.

Setup our CI for a merge queue

---

.github/workflows/ci.yml

I was looking at bumping actions versions, but everything is already up to date. The only action that had an older version was this deadsnakes action (and the codecov action we're having trouble with), and we managed to test 3.13 pre-releases without it (by specifying `3.13` on all matrixes).
Therefore I removed it. If that only works after a beta CPython release, then we can readd this.

Remove unnecessary deadsnakes action

---

.github/workflows/ci.yml

Based on conversation with @webknjaz on Gitter. This ignores pushes on:
- autodeps
- gh's merge queue
- pre-commit.ci's update branch
This trigger is here so people can test their changes against CI without making a PR. The above types of PRs do not need this extra testing, as they will always have a PR (or more generally another event, for gh's merge queue) associated.

Update ignored branches for GHA's push trigger

---

newsfragments/3094.misc.rst
src/trio/_socket.py

Ruff started this in https://github.com/python-trio/trio/pull/3150. While the autofix it has is unsafe (and therefore won't happen in future versions so no need to make a bug report; https://github.com/astral-sh/ruff/pull/14818), why not finish the job and resolve https://github.com/python-trio/trio/issues/3094.

Get rid of using `__` for positional only arguments

---

.codecov.yml
.github/workflows/ci.yml
pyproject.toml
tests/cython/run_test_cython.py
tests/cython/test_cython.pyx

This is a combination of changes that include:
- setting up local coveragepy HTML output to show context
- setting up mapping between site-packages and the repo
- measuring all the Python files in the repo
- including Cython
- making xfails not influence the coverage metric (these test functions may start executing different amounts of lines over time, causing random coverage drops/gains)
- using relative paths for playing nice with Codecov

💄 Refactor the coveragepy config

---

.github/workflows/ci.yml
MANIFEST.in

This patch helps make sure that sdist contents is enough to run tests downstream.

Test sdist contents instead of Git checkout in CI

---

.codecov.yml
newsfragments/3159.misc.rst
pyproject.toml
src/trio/_core/_io_kqueue.py
src/trio/_core/_io_windows.py
src/trio/_core/_run.py
src/trio/_core/_tests/test_io.py
src/trio/_core/_tests/test_run.py
src/trio/_dtls.py
src/trio/_tests/test_dtls.py
src/trio/_tests/test_exports.py
src/trio/_tests/test_socket.py
src/trio/_tests/test_ssl.py
src/trio/_tests/test_subprocess.py
src/trio/_tests/test_timeouts.py
src/trio/_tools/gen_exports.py

Using a combination of more tests and TODO comments that work as coverage pragmas

get and enforce 100% coverage

---

src/trio/_tests/test_highlevel_socket.py
src/trio/_tests/test_socket.py

There's two possible solutions that I see:
- set our `runs-on` to be `macos-15`
- ignore the error, it's not showing something bad anyways
Since the first one is somewhat annoying (we would change it back to `macos-latest` at some point and local tests would fail for people), the second one is ideal. So I implemented that here.

Explain why our MacOS 14 runners failed with CPython 3.13.1

---

.github/workflows/ci.yml

https://github.com/python-trio/trio/pull/3172 took 5 attempts to merge.......
cc @jakkdl

Stop failing CI upon codecov error 503

---

.readthedocs.yml

see https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/

add now required sphinx.configuration in readthedocs.yml

---

newsfragments/3186.misc.rst
src/trio/__init__.py

In this pull request, we publicly re-export `__version__`. This came up when working on https://github.com/python-trio/trio-websocket/pull/193, where some of the unit test code looks at Trio's version for version-dependent things and mypy is not happy about accessing `__version__`.

Publically re-export `__version__`

---

src/trio/_core/_run.py

Type hint issue spotted in https://github.com/python/mypy/pull/18510
Maybe we should wait for that to be merged (and maybe released?) to check this works.

Update type hint for the `CancelStatus.parent` setter

---

.readthedocs.yml
docs/source/conf.py

This also makes RTD install trio instead of depending on `import trio` working. IMO this is more correct.
Supersedes https://github.com/python-trio/trio/pull/3190.

Use importlib.metadata in docs build

---

newsfragments/3166.breaking.rst
newsfragments/3166.misc.rst

Follow up to #3166, I think `breaking` is not accurate because ErrorCode is neither exported nor returned anywhere public.
(this is a kind of unnecessary change but I figure better not make people think the next release has what we would consider a breaking change. I'm fine if we decide to keep it as is.)

Diminish the severity of renaming `ErrorCodes` enum members

---

newsfragments/405.misc.rst
src/trio/_core/_concat_tb.py

Fixes https://github.com/python-trio/trio/issues/405
It's kind of unnecessary since we'll rip this code out anyways once strict exception groups are the only thing supported, but for now it's simpler.

Stop using ctypes for traceback mutation

---

.pre-commit-config.yaml
newsfragments/3201.misc.rst
src/trio/_abc.py
src/trio/_core/_entry_queue.py
src/trio/_core/_instrumentation.py
src/trio/_core/_run.py
src/trio/_core/_tests/test_asyncgen.py
src/trio/_core/_tests/test_ki.py
src/trio/_core/_tests/test_run.py
src/trio/_core/_thread_cache.py
src/trio/_core/_traps.py
src/trio/_file_io.py
src/trio/_highlevel_open_tcp_stream.py
src/trio/_highlevel_serve_listeners.py
src/trio/_path.py
src/trio/_socket.py
src/trio/_ssl.py
src/trio/_tests/test_highlevel_open_tcp_listeners.py
src/trio/_tests/test_highlevel_open_tcp_stream.py
src/trio/_tests/test_highlevel_ssl_helpers.py
src/trio/_tests/test_socket.py
src/trio/_tests/test_ssl.py
src/trio/_tests/test_subprocess.py
src/trio/_tests/test_threads.py
src/trio/_threads.py
src/trio/_util.py
src/trio/testing/_fake_net.py
test-requirements.txt

In https://github.com/python/typeshed/pull/13372, the type of the stdlib's `socket.getaddrinfo` was updated to add a union member for cases where Python was compiled with `--disable-ipv6`. This causes custom resolvers that use the stdlib function to fail mypy
This is probably going to (mypy) break everyone's custom `HostnameResolver`, since the parent type is changing

Update to mypy 1.15

---

newsfragments/2764.bugfix.rst
src/trio/_core/_tests/test_thread_cache.py
src/trio/_core/_thread_cache.py

Fixes https://github.com/python-trio/trio/issues/2764
While we don't provide any sort of guarantees and I think it's tempting to give up on this:
- Python (3.12+) will already warn on this, so they have that handled
- It's friendlier to do the right thing.
As long as people aren't initializing their own thread caches, this should be fine.

Clear worker thread cache after forking

---

.github/workflows/ci.yml
src/trio/_core/_tests/test_run.py
test-requirements.in
test-requirements.txt

See commit messages and discussion in https://github.com/python-trio/trio/issues/3209 for details.

Add xfail for issue 3209, and start testing Python 3.14

---

src/trio/_tests/test_highlevel_open_tcp_listeners.py
src/trio/_tests/test_socket.py
src/trio/_tests/tools/test_gen_exports.py

Fixes #3206.
The main thing is that it turns out that waiting for a socket to fail to connect takes up to 2 seconds on Windows -- so tests that rely on that should be marked `@slow`.
---
This approximately halves local test time on Windows.
```
================================================ slowest 10 durations =================================================
0.75s call     src/trio/_tests/test_exports.py::test_static_tool_sees_all_symbols[jedi-trio]
0.72s call     src/trio/_tests/tools/test_gen_exports.py::test_lint_failure
0.70s call     src/trio/_tests/test_repl.py::test_main_entrypoint
0.52s call     src/trio/_tests/test_util.py::test_coroutine_or_error
0.39s call     src/trio/_tests/test_exports.py::test_static_tool_sees_all_symbols[pylint-trio]
0.33s call …
```

Sprinkle `@slow` on slow tests

---

README.rst
docs/source/code-of-conduct.rst
docs/source/history.rst
docs/source/index.rst
docs/source/reference-core.rst
newsfragments/3216.doc.rst
pyproject.toml
src/trio/_deprecate.py

This PR updates the README to better reflect Trio’s current maturity. The previous wording hadn’t been updated since it was originally written eight years ago and no longer accurately represented Trio’s suitability for production use.
No functional changes—just a documentation update for clarity.

Update stability info in documentation

---

docs/source/_static/hackrtd.css
docs/source/_static/styles.css
docs/source/_templates/layout.html
docs/source/conf.py

Did you know that we have been squishing the logo :'(
... Well, no longer!
---
Also a few other fixes.

Update styles for documentation

---

newsfragments/3183.bugfix.rst
src/trio/_subprocess.py
src/trio/_tests/type_tests/subprocesses.py

Fixes https://github.com/python-trio/trio/issues/3183
I tried out TypedDict here like @decorator-factory recommended and it's nicer, though it's explicitly trading off user experience:
- no defaults listed
- wacky reveal_type at least under mypy
I *think* it's worth it? I doubt people are looking at overloads for the defaults to things.
I still need to add type tests.

Add missing arguments to run_process

---

newsfragments/3224.bugfix.rst
src/trio/_core/_run.py

Noticed this, `start()` was set to `Any | None`, but it never specifically returns `None`, only if you call `started()` with no parameter on a `TaskStatus[None]`. If you're using a different task status, forcing `None` checks is just wrong.

Nursery.start() doesn't specifically return None

---

docs/source/conf.py

References https://github.com/python-trio/trio/issues/3221
An earlier version found these:
```
!!!!!! trio.CancelScope.relative_deadline
!!!!!! trio.MemorySendChannel
!!!!!! trio.MemoryReceiveChannel
!!!!!! trio.MemoryChannelStatistics
!!!!!! trio.SocketStream.aclose
!!!!!! trio.SocketStream.receive_some
!!!!!! trio.SocketStream.send_all
!!!!!! trio.SocketStream.send_eof
!!!!!! trio.SocketStream.wait_send_all_might_not_block
!!!!!! trio._subprocess.HasFileno.fileno
!!!!!! trio.lowlevel.ParkingLot.broken_by
```
Which at least seems right:
- `relative_deadline` is from the above issue
- `SocketStream` has `:undoc-members:` ... for no good reason??
- didn't check the others
Anyways we could probably edit the issue above for a checklist of every one of those so we have easy issues for anyone …

Warn if there's no docstring for documented things

---

newsfragments/2135.bugfix.rst
src/trio/__init__.py
src/trio/_deprecate.py
src/trio/_tests/module_with_deprecations.py
src/trio/_tests/test_deprecate.py

Presumably fixes https://github.com/python-trio/trio/issues/2135 but I haven't checked this and I'm not sure how to test this (as it relies on `cloudpickle` not `pickle`).

Use PEP 562 instead of _ModuleWithDeprecations

---

newsfragments/3133.bugfix.rst
src/trio/_socket.py

Rationale: on some platforms `AI_NUMERICSERV` may not be defined. In particular, old versions of macOS, possibly some other. While affected users are probably few, it is a trivial fix, which makes `trio` usable (for example, `yewtube` app works then).
Credits to @CoolCat467
Closes: https://github.com/python-trio/trio/issues/3133

_socket.py: fix for systems where AI_NUMERICSERV is not defined

---

pyproject.toml
src/trio/_repl.py
src/trio/_tests/check_type_completeness.py
src/trio/_tests/type_tests/raisesgroup.py

In https://github.com/python-trio/trio/issues/3238 I noticed the `truthy-bool` error code seems useful. I combined it with some changes I have locally for another interesting-but-unimpactful error code.
This doesn't catch anything but it's better to lead by example! (all 4 places flagged by `truthy-bool` were us using `assert` to tell various tools that the thing being asserted is used.)

Enable extra error codes for mypy

---

docs/source/conf.py
src/trio/_core/_run.py

ticks off one docstring from #3221
property added in #3010

add relative_deadline docstring

---

src/trio/_path.py
src/trio/_tests/test_path.py
src/trio/_tests/type_tests/path.py

`as_uri` is deprecated in `PurePath`. This commit also introduces a test to ensure users have a workaround that is not deprecated.
Failing test run: https://github.com/python-trio/trio/actions/runs/14393482504/job/40364976912

Switch from `PurePath#as_uri` to `PurePath#joinpath` for our test that PurePath methods get inherited

---

docs-requirements.in
docs-requirements.txt
docs/source/conf.py

Fixes https://github.com/python-trio/trio/issues/3244
As far as I can tell, this requires someone to press buttons in the RTD UI so it's not too useful to leave this up for someone new to Trio to fix.

Move away from hoverxrefs

---

.pre-commit-config.yaml

In this pull request, we change the `crateci/typos` pre-commit hook to use https://github.com/adhtruong/mirrors-typos instead. See https://github.com/crate-ci/typos/issues/390 for full details about why, but basically to support github marketplace the v1 tag is mutable and pre-commit will raise a warning during updates after it changes it to v1. Using a mirror such as this one avoids the problem.

Switch to a `typos` mirror

---

.pre-commit-config.yaml
src/trio/_tests/tools/test_sync_requirements.py
src/trio/_tools/sync_requirements.py
test-requirements.in
test-requirements.txt

In this pull request, we add a local pre-commit hook tool to keep the tool versions in `test-requirements.txt` in sync with the equivalent versions in `.pre-commit-config.yaml` automatically, meaning pre-commit.ci automatic updates are more seamless and there can never be cases where the test versions don't match the pre-commit versions.

Add tool to keep test-requirements in sync with pre-commit

---

.github/workflows/ci.yml
src/trio/_core/_tests/test_run.py
src/trio/_tests/test_exports.py
tox.ini

I'm for some reason not getting mypy fails locally, but disabling `test_static_tool_sees_all_symbols` entirely for 3.14.0b1 rather than trying to dig into why that might be the case
I'm also getting cffi/OpenSSL segfaults locally on 3.14, but that doesn't seem to impact CI so we can probs ignore that one for now

Unbreak CI (3.14 + cython)

---

newsfragments/3232.feature.rst
src/trio/_channel.py
src/trio/_core/_asyncgens.py
src/trio/_core/_exceptions.py
src/trio/_core/_run.py
src/trio/_core/_tests/test_cancel.py
src/trio/_core/_tests/test_cancelled.py
src/trio/_core/_tests/test_run.py
src/trio/_highlevel_generic.py
src/trio/_highlevel_open_tcp_stream.py
src/trio/_subprocess.py
src/trio/_tests/test_threads.py
src/trio/_tests/test_util.py
src/trio/_threads.py
src/trio/_util.py

fixes #3232 by adding a `CancelReason` that's tracked by both `CancelScope` and `CancelStatus` and then used when constructing a `Cancelled` to be raised.
Remaining stuff:
- It's now only tracked in `CancelScope`
- I managed to fix this.. but in a way that created cyclic garbage. So need a better fix

Add message with debugging info to Cancelled

---

pyproject.toml
src/trio/_tests/tools/test_sync_requirements.py
src/trio/_tools/gen_exports.py
src/trio/_tools/mypy_annotate.py
src/trio/_tools/sync_requirements.py

This fixes coverage losses in https://github.com/python-trio/trio/pull/3234

Get coverage back to 100%

---

src/trio/_core/_exceptions.py
src/trio/_core/_tests/test_cancelled.py

This restores backwards compatibility with AnyIO.

Added default value for the "source" parameter in the trio.Cancelled initializer

---

.github/workflows/ci.yml
tox.ini

fixes part of #3267 with the release of https://github.com/cython/cython/releases/tag/3.1.1
I'm getting errors locally when I try to combine it with coverage, so I think there's more to be done, but let's see if CI errors as well
I did look at configuration options for coverage and tox and ultimately couldn't find a better option than `sed`ing `pyproject.toml` (as the CI setup does), though at least did it to a copy in the tox tmp/ directory to not screw with the git working tree.

unpin cython

---

.github/workflows/ci.yml
src/trio/_subprocess.py
src/trio/_tests/test_subprocess.py

A combination of a few changes that I think make things simpler:
- CI stuff I caught a while ago
- mark the CFFI thing as fixed
- fix a type hint/use `_open_process` to simplify type ignore (I was testing out AI models on `_subprocess.py` and those are the valid issues they reported!)

Push some local cleanups

---

src/trio/_highlevel_open_tcp_stream.py

I saw this, not sure when it became unnecessary but I'm pretty sure it's unnecessary now.

Remove unnecessary `start_soon` workaround

---

docs/source/reference-lowlevel.rst
pyproject.toml
src/trio/_channel.py
src/trio/_core/__init__.py
src/trio/_core/_run.py
src/trio/_highlevel_socket.py
src/trio/_path.py
src/trio/_tests/test_unix_pipes.py
src/trio/_timeouts.py
src/trio/_unix_pipes.py
src/trio/lowlevel.py

Fixes https://github.com/python-trio/trio/issues/3071
I'm not *totally* sure about all changes here. Some are likely only because my local installation of Python is 3.13.
Also this is definitely not the cleanest method of doing this :P

Allow documentation builds on Windows

---

src/trio/_unix_pipes.py

Add a note reminding users that `FdStream` might cause "spooky action at a distance" in interactive use-cases, hopefully saving them time during debugging.

Add warning about non-blocking mode and TTYs

---

newsfragments/3332.misc.rst
src/trio/_channel.py
src/trio/_tests/test_channel.py

Wrap exception groups less when raising in `as_safe_channel`

---

newsfragments/3337.bugfix.rst
src/trio/_core/_run.py
src/trio/_tests/test_tracing.py

`.cr_frame` is set to `None` when a coroutine closes, per https://github.com/python/cpython/pull/112428, and while this rarely comes up in practice you can _probably_ guess why I'm opening a PR.

avoid error when `coro.cr_frame is None`
