python-trio/trio

- docs/source/design.rst
Otherwise someone not from "the West" might not get that it's a turn-of-phrase.
> Put a phrase in quotes

- docs/source/reference-hazmat.rst
Any more warning and you would need the blink tag.
> More warning!

- docs/source/design.rst
Add periods and use some code literals to disambiguate "with".
> Normalize a list

- trio/testing.py
Else it isn't much of a "tl;dr" as people will overlook it.
> Make the summary more obvious

- trio/tests/test_signals.py
Caught by looking at the coverage report
> Fix a broken test

- trio/_core/tests/test_ki.py
Whoops, forgot to include these in gh-110
> Small test tweaks

- docs/source/reference-core.rst
- docs/source/reference-hazmat.rst
- docs/source/reference-io.rst
- docs/source/reference-testing.rst
- docs/source/tutorial.rst
- trio/_core/_exceptions.py
- trio/_core/_run.py
- trio/_streams.py
- trio/_sync.py
- trio/_timeouts.py
- trio/socket.py
- trio/testing.py
- trio/tests/test_testing.py
In part based on feedback from @brettcannon, @dimaqq, and discussion
in #66. Review welcome!
Closes: #106, #66
> A number of doc updates

- trio/_core/tests/test_ki.py
This is being flaky on Windows, almost certainly due to a bug in
CPython 3.5.{0,1,2,3} and 3.6.{0,1}:
https://bugs.python.org/issue30038
More details in gh-119.
I've submitted (what I think is) a fix to CPython, but in the mean
time the random appveyor failures are pretty annoying and I don't see
any way to fix them except wait for CPython to make a new release, so
as a temporary measure this commit adds some retry logic to this
test.
This is an ugly hack and should be removed as soon as possible.
(Unfortunately that probably won't be until after we can drop 3.6
support...)
> Work around flakiness in test_ki_wakes_us_up

- trio/_core/tests/test_ki.py
This makes the workaround more realistic, more precisely targeted, and
less messy code-wise.
> Different and better workaround for gh-119

- README.rst
- docs/source/index.rst
- docs/source/tutorial.rst
- docs/source/tutorial/tasks-intro.py
- setup.py
- try to make our landing pages friendlier and more interlinked
- some small tweaks to the tutorial
> Misc doc cleanups

- ci/rtd-requirements.txt
While we're waiting for a release with rtfd/sphinx_rtd_theme#381
included.
> [rtd] Attempt to install a dev version of rtd

- docs/source/tutorial.rst
Some early user feedback suggests that this is possible to
miss (gh-135), and it's important and kinda subtle (it involves an
invisible function call!). So let's make sure to point it out
explicitly the very first time we see a call to open_nursery, and
reinforce it as we go.
> [doc] Emphasize that parenting is a full-time job in the tutorial

- trio/_core/tests/test_ki.py
Inspired by this failure:
https://ci.appveyor.com/project/njsmith/trio/build/1.0.330/job/s0cd9tpyamdtbai7
> Another attempt to fix intermittent failure in test_ki_wakes_us_up

- ci/rtd-requirements.txt
- docs/source/conf.py
- We no longer have a local extension, so no need to munge sys.path
- sphinx 1.6 is out! We don't need to monkeypatch anymore! (I think)
- we can use sphinx 1.6 on RTD too!
> [docs] Small cleanups to sphinx config

- trio/_core/_run.py
- trio/_core/_traps.py
- trio/_core/tests/test_run.py
...or other similar libraries.
> Give better error messages if users mix us up with asyncio

- docs/source/reference-io.rst
- setup.py
- trio/socket.py
- trio/tests/test_socket.py
> Make trio.socket properly async-correct and IDNA-correct

- trio/_path.py
- trio/tests/test_path.py
I realized in #217 that our repr isn't consistent.
> path: repr path value in repr

- docs/source/conf.py
- docs/source/reference-io.rst
- docs/source/reference-testing.rst
- trio/abc.py
- trio/socket.py
- trio/tests/test_socket.py
See gh-170.
Still needs tests.
> Make it possible to override hostname resolution and socket behavior

- trio/_threads.py
> Remove stray print() call

- trio/_core/_wakeup_socketpair.py
This might make a difference on Windows, and definitely doesn't hurt.
> Set TCP_NODELAY on the wakeup socket

- docs/source/reference-core.rst
Thanks to @matham for catching it:
https://github.com/python-trio/trio/pull/298#issuecomment-323878939
> [docs] Fix typo

- notes-to-self/print-task-tree.py
> Add example output to notes-to-self/print-task-tree.py

- ci/travis.sh
I really need to stop using bash for things.
> [travis] fix stupid typo that was disabling pypy nightly builds

- .travis.yml
- ci/travis.sh
Fixes gh-332 and adds a temporary workaround for gh-334.
> Two fixes to unblock our CI

- trio/_core/_run.py
- trio/_core/tests/test_run.py
> Report instrument errors via logging

- trio/tests/test_highlevel_open_tcp_listeners.py
@nmalaguti is reporting that on a particular VPS they have access to,
sometimes, the test_open_tcp_listeners_backlog test is blowing up with
EMFILE and breaking other tests. It seems to involve the kernel
switching to using syn cookies, and then suddenly infinitely many
connection attempts can appear to succeed.
A real fix would be to make the test robust against syncookies, but
I'm not yet sure how to do that. In the mean time this at least should
make the test more robustly clean up after itself, so that this causes
a well-defined failure without shrapnel flying out to hit other tests.
> Make measure_backlog more robust against weird errors

- .travis.yml
- Jenkinsfile
- ci/travis.sh
> Add Jenkinsfile for MacOS testing on ci.cryptography.io

- newsfragments/277.bugfix.rst
- trio/_socket.py
- trio/tests/test_socket.py
> Fix corner cases in implicit resolution to better match stdlib

- appveyor.yml
- ci/travis.sh
- test-requirements.txt
Hopefully this will help us diagnose weird freezes like gh-379
> Enable pytest-faulthandler

- .style.yapf
- ci/travis.sh
- trio/_core/_io_windows.py
- trio/_core/_multierror.py
- trio/_core/_run.py
- trio/_core/tests/test_ki.py
- trio/_core/tests/test_run.py
- trio/_core/tests/tutil.py
- trio/_socket.py
- trio/_ssl.py
- trio/_util.py
- trio/testing/_memory_streams.py
- trio/tests/test_highlevel_open_tcp_listeners.py
- trio/tests/test_ssl.py
- trio/tests/test_testing.py
See individual commit messages for the full saga.
> Upgrade our yapf from 0.17.0 → 0.19.0

- newsfragments/395.misc
- trio/_core/_traps.py
> Simplify implementation of primitive traps like wait_task_rescheduled

- trio/_file_io.py
- trio/_path.py
- trio/_util.py
- trio/tests/test_file_io.py
- trio/tests/test_highlevel_open_unix_stream.py
- trio/tests/test_path.py
> Replace "path.__fspath__()" with "fspath(path)"

- docs/source/index.rst
- setup.py
> Fix illumos spelling

- docs/source/design.rst
- docs/source/index.rst
- setup.py
I don't know what my fingers are thinking.
(Cf gh-442.)
> Fix illumos spelling, again

- trio/_util.py
- trio/tests/test_util.py
> [testing] Add tests for fspath.

- .travis.yml
- ci/travis.sh
- trio/_deprecate.py
- trio/tests/test_deprecate.py
- trio/tests/test_ssl.py
> Try switching to using Travis's pypy build

- newsfragments/461.bugfix.rst
- newsfragments/461.feature.rst
- trio/_core/_io_windows.py
- trio/_core/_ki.py
- trio/_core/tests/test_ki.py
- trio/_signals.py
- trio/_util.py
- trio/tests/test_util.py
> Add better KeyboardInterrupt handling with broken threads.

- docs/source/tutorial.rst
Thanks for the great work on Trio 😊
> Fix typo in tutorial (s/it's/its)

- README.rst
- setup.py
- trio/_core/_run.py
- trio/_core/tests/test_ki.py
- trio/_highlevel_generic.py
- trio/_util.py
- trio/testing/_sequencer.py
- trio/tests/test_highlevel_ssl_helpers.py
- trio/tests/test_ssl.py
- trio/tests/test_util.py
Resolves #418 
I don't think this needs a newsfragment or a documentation change.
> Use async_generator.asynccontextmanager

- ci/travis.sh
> Fix wheel install for Jenkins sierra-python3.5 build

- trio/_core/_run.py
> Duplicate "the"

- trio/testing/_trio_test.py
Pretty cool to have this with pytest-trio fixtures ;-)
> trio_test accept Instrument as parameter

- trio/_path.py
- trio/tests/test_path.py
> Improve trio.Path.iterdir

- trio/tests/test_highlevel_open_tcp_listeners.py
> Fix coverage flapping in test_highlevel_open_tcp_listeners

- docs/source/contributing.rst
- trio/_ssl.py
> Fix link to node.js code review docs

- trio/_core/_run.py
This is important because Cython has its own generator/coroutine
types that are interchangeable with the ones built into the
interpreter, but not (always) detectable by the inspect module.
There's some more checks in trio/_core/_ki.py that still use the
inspect module. Unfortunately, they're using the inspect.is*function
forms, which are not easily replaceable by ABC checks. Fortunately,
usage of @enable_ki_protection and @disable_ki_protection are very
rare, so hopefully this won't affect too much?
Helps with gh-550, but doesn't fix it.
> Use ABCs instead of inspect to detect generators/coroutines

- .style.yapf
- test-requirements.in
- test-requirements.txt
- trio/_core/_io_windows.py
- trio/_core/_run.py
- trio/_socket.py
- trio/_sync.py
- trio/testing/_mock_clock.py
- trio/tests/test_highlevel_serve_listeners.py
- trio/tests/test_sync.py
- trio/tests/test_testing.py
I'm also curious how the update bots will handle this.
> Bump yapf to 0.24, and re-run with new version

- notes-to-self/estimate-task-size.py
- notes-to-self/graceful-shutdown-idea.py
- notes-to-self/thread-dispatch-bench.py
These are somewhat useful and I've had them lying around forever; now
I want to get them out of my list of uncommitted files :-).
> Add some more notes-to-self

- ci/travis.sh
> Temporarily disable coverage reporting on 3.8-dev

- .travis.yml
Since Jenkins is acting screwy and not letting people see the logs
:-(.
It's possible that this will cause gh-584 to start happening again,
so I guess we'll just have to watch out for that...
Fixes gh-749
> Re-enable macOS testing on Travis

- trio/_subprocess/linux_waitpid.py
> Replace StubLimiter with CapacityLimiter(inf)

- docs/source/reference-io.rst
- trio/_subprocess.py
I just looked at the subprocess docs in RTD … surprise.
> Read new docs, find a mistake.

- docs/source/contributing.rst
I spent years trying to remember where I saw this essay; now that I
found it let's put it in the docs quick before I forget again :-).
> Add another link about reviewing PRs

- newsfragments/251.feature.rst
- trio/_socket.py
- trio/tests/test_socket.py
WIP as `_socket.fromfd` doesn't work properly.  
Also, shouldn't work on mac...
Fixes: #251
> add sniff sockopts

- ci/rtd-requirements.txt
- docs/source/conf.py
- trio/_threads.py
> Bump sphinx from 1.8.5 to 2.0.0 and fix doc build accordingly

- newsfragments/1017.doc.rst
- trio/_abc.py
- trio/_channel.py
- trio/_file_io.py
- trio/_highlevel_generic.py
- trio/_highlevel_socket.py
- trio/_signals.py
- trio/_socket.py
- trio/_ssl.py
- trio/_subprocess.py
- trio/_sync.py
- trio/_threads.py
- trio/_timeouts.py
- trio/_unix_pipes.py
- trio/_util.py
- trio/_wait_for_object.py
- trio/tests/test_util.py
- trio/tests/test_wait_for_object.py
Refactor of trio/*.py to use public names instead of _core 
Per issue #1017 
- Refactor/Bugfix Pull Request
First time contributing to this project, please let me know if/when I am in error.
> Refactor: Changing _core to public names

- newsfragments/960.bugfix.rst
- trio/_path.py
- trio/tests/test_path.py
Fixes #960 and applies to #917.
> Generate async classmethods for pathlib.Path

- docs/source/contributing.rst
Link to towncrier's output, so new people can click and see what this is for
before having to install & run it.
> Contrib guide: Link to the release notes

- newsfragments/762.misc.rst
- trio/_highlevel_open_tcp_stream.py
- trio/tests/test_highlevel_open_tcp_stream.py
> Update happy eyeballs default timeout for RFC 8305

- newsfragments/676.bugfix.rst
- trio/_core/_ki.py
- trio/_core/tests/test_ki.py
> Enabled KeyboardInterrupt protection inside __del__ methods

- newsfragments/674.misc.rst
- trio/_core/_exceptions.py
- trio/_core/tests/test_run.py
> Added readable str for Cancelled object

- trio/_core/tests/test_multierror.py
- trio/_core/tests/test_run.py
Hopefully this should fix our CI.
> Ignore deprecation warnings about @coroutine decorator

- ci.sh
split off the codecov pypy3 results because we're suspicious pypy might be causing the weird coverage issues we're seeing
> Sort out coverage issues on pypy3

- trio/_core/_io_windows.py
This comment was speculating about how to implement
WaitForSingleObject, which landed ages ago.
> Delete an obsolete comment

- setup.py
- trio/_core/_io_windows.py
We asked Armin to add these so it would be rude not to use them:
https://bitbucket.org/cffi/cffi/issues/394/
https://bitbucket.org/cffi/cffi/issues/395/
> Take advantage of new features in cffi 1.12

- trio/_core/_entry_queue.py
- trio/_core/_io_epoll.py
- trio/_core/_io_kqueue.py
- trio/_core/_parking_lot.py
- trio/_core/_run.py
- trio/_core/tests/test_run.py
- trio/_sync.py
- trio/testing/_sequencer.py
- trio/tests/test_abc.py
- trio/tests/test_highlevel_generic.py
>  replace attr.Factory()

- newsfragments/984.feature.rst
- trio/_core/_entry_queue.py
- trio/_core/_io_epoll.py
- trio/_core/_io_kqueue.py
- trio/_core/_io_windows.py
- trio/_core/_run.py
Since we don't dynamically add any attributes to that class and attrs allow us to generate slots automatically, we should use them whenever possible.
> Use slots on whenever possible

- docs/source/history.rst
- docs/source/reference-hazmat.rst
- newsfragments/878.removal.rst
- trio/__init__.py
- trio/_core/__init__.py
- trio/_core/_io_epoll.py
- trio/_core/_io_kqueue.py
- trio/_core/_io_windows.py
- trio/_core/_wakeup_socketpair.py
- trio/_core/tests/test_io.py
- trio/_socket.py
- trio/_unix_pipes.py
- trio/hazmat.py
> Standardize the names of wait_* and notify_closing across platforms

- docs/source/contributing.rst
Closes #1111 
Let me know if you want to change any of the wording/phrasing!
> Added paragraph for automatically closing issues

- ci.sh
For details see: https://github.com/python-trio/trio/pull/1221#issuecomment-536447141
> Attempt to fix Azure Pipelines

- ci.sh
The hope is that this will finally resolve gh-1231.
> [ci] Try retrying curl if it fails

- trio/_path.py
Fix issue #1308.
I wrote the simplest fix, just to get things started.
> Run the iteration for glob, rgblob and iterdir in a thread

- newsfragments/1308.bugfix.rst
> Add missing newfragment for issue #1308

- .travis.yml
This reverts commit 327d6f4d772fdcc8b281a2da96a94cefdb9f70a0. Closes #1402
> Revert "Allow dev builds to fail"

- trio/_channel.py
Ripped from the gitter channel. Might help.
> Add note about cancellation and memory channels

- setup.py
> Bump minimum cffi version to 1.14.0

- docs/source/awesome-trio-libraries.rst
A new Trio-native Redis library.
> Add redio to awesome-trio-libraries.

- trio/tests/test_subprocess.py
> Fix flaky 'test_signals' in test_subprocess.py

- docs/source/awesome-trio-libraries.rst
Tenacity is a library for retrying functions, which works with async/await.
> Added tenacity library to awesome trio libraries

- ci.sh
> Use --insecure when fetching LSP installers in CI

- docs/source/awesome-trio-libraries.rst
Great for people who want to program for the web – no node, javascript, and related nonsense. ;-)
Also no documentation yet, but getting there.
> Add DeFramed to Trio's awesomeness.

- .github/workflows/ci.yml
- ci.sh
- newsfragments/1499.bugfix.rst
- trio/tests/test_socket.py
> Test on Alpine, and make tests pass

- ci.sh
Pointed out by Quentin here:
https://github.com/python-trio/trio/pull/1510#issuecomment-627069882
> Fix filesystem CI comments

- notes-to-self/win-waitable-timer.py
Getting this out of my working tree
> Note-to-self for windows WaitableTimer objects

- trio/_core/_ki.py
- trio/_core/_run.py
- trio/_core/_thread_cache.py
- trio/_core/_wakeup_socketpair.py
> Remove unused imports

- .yapfignore
> Remove now-unused .yapfignore file

- docs/source/awesome-trio-libraries.rst
As discussed briefly with @njsmith in chat.
These are the only two projects I know of presently but I'm happy to dig for some more before this is merged.
> Start an RPC list

- .github/workflows/ci.yml
- ci.sh
We're now testing docs via the ReadTheDocs pull request integration.
> Remove docs check

- docs/source/reference-core.rst
> Improved docs related to child cancellation

- newsfragments/1630.bugfix.rst
- trio/_core/_multierror.py
- trio/_core/tests/test_multierror.py
- trio/_core/tests/test_multierror_scripts/simple_excepthook_partial.py
> Fix importing trio while sys.excepthook is a partial

- trio/_core/_run.py
> Remove "Returns" section from Nursery.start_soon docs.

- newsfragments/959.deprecated.rst
- trio/_ssl.py
- trio/tests/test_ssl.py
Another attempt at #1857 to get builds.sr.ht to run.
> Remove deprecated max refill bytes take 2

- README.rst
- reduce verbiage
- correct punctuation
- strengthen intent
> (docs) update README.rst

- trio/_core/_io_windows.py
Ok, been a long time since I looked at this (#937), but had another go at it recently.  Here's a working example of using IOCP with 
[ReadDirectoryChanges](/lojack5/ReadDirectoryChanges).  Let me know if this needs a test or more documentation.
> WindowsIOManager.wait_overlapped returns CompletionKeyEventInfo

- docs/source/awesome-trio-libraries.rst
Inspired by the recent addition of Qtrio by @altendky in #1886. 💡
> Add trio-parallel to the awesome list

- docs/source/awesome-trio-libraries.rst
* asyncakumuli
* asyncowfs
* DistKV (already mentioned in DistMQTT)
Also updated the URL for DistKV to point to the MoaT project on github.
> Additions to the Trio-Awesome list

- newsfragments/1948.feature.rst
- trio/_sync.py
> implement Event directly with wait_task_rescheduled rather than ParkingLot

- LICENSE.MIT
https://github.com/cdfoundation/foundation/blob/master/copyright.md#copyright-notices
Fixes #1972
> add copyright notice to LICENCE.MIT

- docs-requirements.txt
- test-requirements.txt
Closes #2078
Creating a new pull request to get builds.sr.ht to build.
> Bump pygments from 2.7.4 to 2.9.0

- docs/source/awesome-trio-libraries.rst
Added info about [aio-databases](https://github.com/klen/aio-databases) and [peewee-aio](https://github.com/klen/peewee-aio)
> Update awesome trio libraries

- trio/_util.py
Noticed some unused imports and a few typos. Decided to clean them up.
> Minor cleanup of utils

- .github/workflows/autodeps.yml
Changes in the working tree report 1 with this command, and 1 is falsy in bash.
> Invert no changes check in autodeps

- .github/workflows/autodeps.yml
Hopefully this fixes this. Even if it doesn't, this should print out more detailed information for debugging (such as local changes).
> Some small improvements before debugging autodeps

- docs/source/awesome-trio-libraries.rst
Adding the linter created by me and @Zac-HD to the list of Tools and Utilities.
> add flake8-trio to list of Tools and Utilities in Awesome Trio Libraries

- .github/workflows/autodeps.yml
This should fix autodeps once and for all. Hopefully!
Seems to work here: https://github.com/python-trio/trio/actions/runs/4899533479/jobs/8749560235#step:6:57
> Make sure the index is synced before diff-index

- .github/workflows/autodeps.yml
This is a really small change I sniped (sorry @Sxderp, there's other "good first issue" labelled stuff if you want one!) cause nobody was doing it and so that I could get some practice with GitHub Mobile's new editing files feature! As such, let me know if I messed anything up!
> Readd accidental "git" delete

- check.sh
- trio/_tests/test_exports.py
various small fixes for issues that arose when running tests locally / in tox
> don't open git diff in pager, mypy export tests now error on any mypy output

- docs/source/releasing.rst
Fixes https://github.com/python-trio/trio/issues/2695
This just updates the checklist (and clears up a bit of language I was confused about until I had to do the step... the second time around. Not sure why I didn't have to earlier).
> Make sure to make GitHub releases

- .gitattributes
Quickly merging this small one to ease merging my typechecking branches into eachother.
> set merge strategy for verify_types.json in .gitattributes

- setup.py
I'll make a test release on TestPyPI when I feel like it (probably in a few days :( ). I think this should work, though.
> Add link to changelog on PyPI page

- trio/_channel.py
Noticed this quite a while ago but I've been getting super side tracked :(
This hopefully won't fail anything.
> Address an old comment waiting for `Self` support

- newsfragments/2611.bugfix.rst
Issue #2611, PR #2826
Accidentally forgot to add the requested newsfragment.
Not super happy with my sentence construction here, feel free to improve it or suggest changes.
> add newsfragment for issue #2611, PR #2826

- docs/source/history.rst
- newsfragments/2855.bugfix.rst
- trio/_version.py
Patch fix for Anaconda crashes
> Bump version to 0.23.1

- newsfragments/2861.misc.rst
- pyproject.toml
> do not depend on exceptiongroup pre-release

- .github/workflows/autodeps.yml
> Update `black` invocation for new structure

- src/trio/_core/_ki.py
- src/trio/_core/_run.py
- src/trio/_tests/test_util.py
- test-requirements.txt
This pull request handles updating the version of mypy we use for testing to `1.11.0`.
> Update to mypy 1.11.0

- ci.sh
Fixes https://github.com/python-trio/trio/issues/3057
> Constrain dependencies to our requirements.txt file

- .github/workflows/ci.yml
Refs https://github.com/python-trio/trio/issues/2885
This seems to just work as is.
> Test PyPy 3.10 on both Windows and MacOS

- pyproject.toml
https://peps.python.org/pep-0639/ and https://setuptools.pypa.io/en/latest/history.html#v77-0-0
> Utilize PEP 639

- .github/workflows/ci.yml
Testing whether https://github.com/codecov/codecov-cli/issues/672 was fixed
> Bump codecov CLI version to 10.4.0

- .github/workflows/ci.yml
PyPy's latest release only supports 3.11.
> Drop PyPy 3.10
